// Builder's Knowledge Garden — Architectural Styles Library
// 30 styles, each with metadata that powers Browse & Pick, Style Guide, and Surprise Me
// Every style has: id, name, era, region, palette (CSS colors), characteristics, famous examples, dreamSeed

export interface ArchStyle {
  id: string;
  name: string;
  emoji: string;
  era: string;
  region: string;
  palette: string[];        // 3–4 hex colors representing the material palette
  tagline: string;          // one punchy line
  characteristics: string[];// 3–5 defining features
  materials: string[];      // key materials
  famous: string[];         // 2–3 famous examples
  dreamSeed: string;        // sentence fragment that feeds the NL parser
  costTier: "affordable" | "moderate" | "premium" | "ultra";
  tags: string[];
}

export const ARCHITECTURE_STYLES: ArchStyle[] = [
  // ─── RESIDENTIAL MODERN ──────────────────────────────────
  {
    id: "desert-modernist",
    name: "Desert Modernist",
    emoji: "🏜️",
    era: "1950s–present",
    region: "American Southwest",
    palette: ["#C4A882", "#8B7355", "#E8E0D0", "#4A3728"],
    tagline: "Concrete and glass dissolving into the landscape",
    characteristics: ["Low horizontal profile", "Flat or shallow-pitched roof", "Indoor-outdoor flow", "Natural material palette", "Minimalist mass"],
    materials: ["Rammed earth", "Concrete", "Steel", "Desert wood", "Stone"],
    famous: ["Kaufmann Desert House by Richard Neutra", "Elrod House by John Lautner", "Taliesin West by Frank Lloyd Wright"],
    dreamSeed: "A low-slung desert modern home with rammed earth walls, flat roof, floor-to-ceiling glass, and a seamless connection to the landscape",
    costTier: "premium",
    tags: ["modern", "desert", "sustainable", "indoor-outdoor"],
  },
  {
    id: "japandi",
    name: "Japandi",
    emoji: "🎋",
    era: "2010s–present",
    region: "Japan / Scandinavia fusion",
    palette: ["#F5F0E8", "#8B8070", "#2C2C2C", "#A8B89A"],
    tagline: "Wabi-sabi meets hygge in perfect calm",
    characteristics: ["Warm minimalism", "Natural wood tones", "Functional simplicity", "Connection to nature", "Quiet palette"],
    materials: ["White oak", "Bamboo", "Linen", "Concrete", "Rice paper"],
    famous: ["SANAA works", "Kengo Kuma residential projects", "Norm Architects interiors"],
    dreamSeed: "A Japandi home with warm oak floors, shoji screens, wabi-sabi textures, engawa deck, and soaking tub with forest view",
    costTier: "premium",
    tags: ["japanese", "scandinavian", "minimalist", "calm", "nature"],
  },
  {
    id: "pacific-northwest-modern",
    name: "Pacific Northwest Modern",
    emoji: "🌲",
    era: "1960s–present",
    region: "Pacific Northwest USA",
    palette: ["#2D4A2D", "#8B7355", "#C8B89A", "#1A1A1A"],
    tagline: "Timber and glass in a forest cathedral",
    characteristics: ["Post-and-beam structure", "Exposed timber", "Massive windows to trees", "Green roofs", "Stone fireplaces"],
    materials: ["Douglas fir", "Cedar", "Stone", "Steel", "Triple-pane glass"],
    famous: ["Haines House by Olson Kundig", "Any Olson Kundig cabin", "Longbranch Improvement Club"],
    dreamSeed: "A Pacific Northwest modern home with exposed timber beams, floor-to-ceiling glass looking into old-growth forest, stone fireplace, and wrap-around deck",
    costTier: "premium",
    tags: ["timber", "nature", "modern", "northwest", "forest"],
  },
  {
    id: "california-modern",
    name: "California Modern",
    emoji: "☀️",
    era: "1950s–present",
    region: "California coast",
    palette: ["#F5F0E0", "#B8A882", "#5B8DB8", "#4A7A4A"],
    tagline: "White plaster, warm wood, infinite ocean",
    characteristics: ["Sliding glass walls to outdoor living", "Flat or shed roof", "Open floor plan", "Outdoor kitchen", "Pool as architectural element"],
    materials: ["White stucco", "Teak", "Concrete", "Steel", "Tile"],
    famous: ["Case Study Houses", "Paul Rudolph beach houses", "Any Malibu compound"],
    dreamSeed: "A California modern home with white plaster walls, sliding glass to an outdoor living room, pool merging with ocean views, warm teak details",
    costTier: "ultra",
    tags: ["coastal", "modern", "indoor-outdoor", "pool", "california"],
  },
  // ─── CLASSIC / TRADITIONAL ───────────────────────────────
  {
    id: "mediterranean",
    name: "Mediterranean",
    emoji: "🫒",
    era: "Ancient–present",
    region: "Southern Europe / Middle East",
    palette: ["#D4A84B", "#8B4513", "#F5E6C8", "#4A7A4A"],
    tagline: "Terracotta, arches, and olive trees forever",
    characteristics: ["Clay tile roof", "Arched doorways and windows", "Stucco exterior", "Interior courtyard", "Outdoor dining terraces"],
    materials: ["Terracotta tile", "Stucco", "Stone", "Wrought iron", "Cypress wood"],
    famous: ["Getty Villa, LA", "Any Tuscan farmhouse", "Greek island vernacular architecture"],
    dreamSeed: "A Mediterranean home with clay tile roof, arched colonnades, stone courtyard with fountain, terracotta floors, and pergola-covered outdoor dining",
    costTier: "moderate",
    tags: ["classic", "outdoor", "courtyard", "warm", "european"],
  },
  {
    id: "craftsman",
    name: "American Craftsman",
    emoji: "🏡",
    era: "1905–1930, revival 1990s–present",
    region: "North America",
    palette: ["#6B4226", "#8B7355", "#C4A882", "#2C3E2D"],
    tagline: "Honest materials, human scale, handcrafted soul",
    characteristics: ["Covered front porch with tapered columns", "Exposed rafter tails", "Built-in cabinetry", "Natural materials", "Low-pitched roof"],
    materials: ["Wood siding", "Stone or brick base", "Copper", "Oak trim", "Arts & Crafts tile"],
    famous: ["Gamble House, Pasadena", "Greene & Greene bungalows", "Stickley furniture"],
    dreamSeed: "A Craftsman bungalow with wide covered front porch, tapered columns, built-in window seats and bookshelves, exposed timber details, Arts & Crafts tile",
    costTier: "moderate",
    tags: ["traditional", "porch", "craft", "residential", "classic"],
  },
  {
    id: "farmhouse-modern",
    name: "Modern Farmhouse",
    emoji: "🚜",
    era: "2010s–present",
    region: "Rural America",
    palette: ["#FFFFFF", "#2C2C2C", "#8B7355", "#C4A882"],
    tagline: "Board-and-batten soul meets clean modern line",
    characteristics: ["Black window frames", "Board and batten siding", "Metal roof", "Wraparound porch", "Open barn doors"],
    materials: ["White painted wood", "Black steel windows", "Reclaimed wood", "Shiplap", "Board and batten"],
    famous: ["Chip and Joanna Gaines aesthetic", "Any modern farmhouse from Architectural Digest"],
    dreamSeed: "A modern farmhouse with board-and-batten exterior, black window frames, metal roof, wraparound porch, shiplap interiors, and an open kitchen with island",
    costTier: "moderate",
    tags: ["farmhouse", "modern", "porch", "residential", "popular"],
  },
  {
    id: "mid-century-modern",
    name: "Mid-Century Modern",
    emoji: "🛋️",
    era: "1945–1969",
    region: "USA / International",
    palette: ["#D4A84B", "#8B4513", "#2C2C2C", "#4A7A4A"],
    tagline: "Post-war optimism frozen in amber",
    characteristics: ["Flat planes and clean lines", "Large glass walls", "Organic forms", "Open floor plan", "Integration with landscape"],
    materials: ["Brick", "Glass", "Concrete block", "Warm wood", "Stone"],
    famous: ["Eames House", "Fallingwater by Wright", "Glass House by Philip Johnson"],
    dreamSeed: "A mid-century modern home with flat roof, clerestory windows, open floor plan, brick accent wall, Eames furniture, and seamless glass to the garden",
    costTier: "premium",
    tags: ["mid-century", "classic", "iconic", "open-plan", "glass"],
  },
  // ─── URBAN / INDUSTRIAL ──────────────────────────────────
  {
    id: "brooklyn-industrial",
    name: "Industrial Loft",
    emoji: "🏭",
    era: "1980s–present",
    region: "Urban America / Europe",
    palette: ["#4A4A4A", "#8B7355", "#C0392B", "#2C2C2C"],
    tagline: "Factory bones, residential soul",
    characteristics: ["Exposed brick walls", "Steel beams and columns", "Concrete floors", "Double-height ceilings", "Oversized windows"],
    materials: ["Exposed brick", "Steel", "Concrete", "Reclaimed wood", "Black iron pipe"],
    famous: ["Any Tribeca loft conversion", "Soho House New York", "Ace Hotel interiors"],
    dreamSeed: "An industrial loft conversion with exposed brick, steel beams, 16-foot ceilings, concrete floors, mezzanine bedroom, and a chef's kitchen with concrete island",
    costTier: "premium",
    tags: ["industrial", "urban", "loft", "brick", "open"],
  },
  {
    id: "brutalist",
    name: "New Brutalism",
    emoji: "🏛️",
    era: "1950s–1970s, revival 2010s–present",
    region: "Global",
    palette: ["#888888", "#4A4A4A", "#C8C0B8", "#2C2C2C"],
    tagline: "Raw concrete as poetry",
    characteristics: ["Exposed board-form concrete", "Massive geometric forms", "Dramatic cantilevers", "Raw material honesty", "Monolithic presence"],
    materials: ["Board-formed concrete", "Steel", "Glass", "Corten steel", "Raw stone"],
    famous: ["Habitat 67 Montreal", "Boston City Hall", "Barbican London"],
    dreamSeed: "A new brutalist home with board-formed concrete walls, dramatic cantilevered volumes, narrow slot windows, indoor courtyard with single tree, raw material palette",
    costTier: "ultra",
    tags: ["brutalist", "concrete", "bold", "architectural", "statement"],
  },
  // ─── COASTAL / TROPICAL ──────────────────────────────────
  {
    id: "tropical-balinese",
    name: "Tropical Balinese",
    emoji: "🌴",
    era: "Ancient–present",
    region: "Bali / Southeast Asia",
    palette: ["#2C4A2C", "#8B6914", "#C4A050", "#1A1A1A"],
    tagline: "Jungle luxury where walls disappear",
    characteristics: ["Open-air pavilion structure", "Thatched or terracotta roof", "Infinity pool in jungle", "Hand-carved wood details", "Natural ventilation"],
    materials: ["Teak", "Alang-alang thatch", "Volcanic stone", "Bamboo", "Carved stone"],
    famous: ["Como Shambhala Estate", "Four Seasons Bali", "COMO Shambhala Villa"],
    dreamSeed: "A Balinese tropical villa with open-air pavilions, alang-alang thatched roofs, infinity pool overlooking jungle, hand-carved teak, and outdoor bathroom with garden",
    costTier: "ultra",
    tags: ["tropical", "luxury", "open-air", "pool", "exotic"],
  },
  {
    id: "coastal-hampton",
    name: "Hamptons Shingle Style",
    emoji: "⛵",
    era: "1880s–present",
    region: "Northeastern USA",
    palette: ["#D4C8B0", "#4A6741", "#8B8070", "#FFFFFF"],
    tagline: "Atlantic cedar, white trim, and summer forever",
    characteristics: ["Cedar shingle exterior", "Dormers and gambrel roof", "Covered porches", "White painted interiors", "Wainscoting and trim"],
    materials: ["White cedar shingles", "White oak floors", "Bluestone", "White trim", "Rope and brass hardware"],
    famous: ["Any Hamptons estate", "Robert A.M. Stern shingle style houses"],
    dreamSeed: "A Hamptons shingle style home with weathered cedar exterior, double-height entry, white painted interiors, covered porch, pool terrace, and summer kitchen",
    costTier: "ultra",
    tags: ["coastal", "classic", "shingle", "porch", "east-coast"],
  },
  // ─── GLOBAL VERNACULAR ───────────────────────────────────
  {
    id: "tuscan-farmhouse",
    name: "Tuscan Farmhouse",
    emoji: "🏛️",
    era: "Medieval–present",
    region: "Tuscany, Italy",
    palette: ["#D4A84B", "#8B4513", "#C4B08A", "#4A7A4A"],
    tagline: "Stone walls, terracotta, and 500 years of cooking",
    characteristics: ["Stone masonry walls", "Terracotta tile roofing", "Exposed timber beams", "Stone arched cellar", "Olive and cypress setting"],
    materials: ["Pietra serena stone", "Terracotta tile", "Chestnut beams", "Wrought iron", "Travertine"],
    famous: ["Any Chianti farmhouse", "Francis Ford Coppola's Rubicon Estate"],
    dreamSeed: "A Tuscan stone farmhouse with terracotta tile roof, exposed chestnut beams, terracotta floors, wine cellar, outdoor wood-fired pizza oven, and olive grove courtyard",
    costTier: "premium",
    tags: ["italian", "stone", "traditional", "outdoor", "rustic"],
  },
  {
    id: "spanish-colonial",
    name: "Spanish Colonial Revival",
    emoji: "🌹",
    era: "1600s–present",
    region: "Spain / Latin America / California",
    palette: ["#C4501A", "#D4A84B", "#F5E6C8", "#2C6B2C"],
    tagline: "Courtyard, fountain, and the scent of jasmine",
    characteristics: ["Red clay tile roof", "White stucco walls", "Interior courtyard with fountain", "Wrought iron balconies", "Arched colonnades"],
    materials: ["Adobe", "White stucco", "Talavera tile", "Wrought iron", "Terra cotta"],
    famous: ["Mission Santa Barbara", "El Fureidis Santa Barbara", "Any Montecito estate"],
    dreamSeed: "A Spanish Colonial home with red clay tile roof, white stucco walls, interior courtyard with tiled fountain, wrought iron railings, Talavera tile kitchen, and jacaranda-shaded patio",
    costTier: "premium",
    tags: ["spanish", "courtyard", "tile", "california", "classic"],
  },
  {
    id: "japanese-traditional",
    name: "Japanese Traditional",
    emoji: "⛩️",
    era: "700 CE–present",
    region: "Japan",
    palette: ["#2C2C2C", "#8B7355", "#C8B89A", "#4A7A4A"],
    tagline: "Simplicity so perfect it becomes sacred",
    characteristics: ["Engawa wraparound porch", "Shoji sliding screens", "Tatami rooms", "Exposed post-and-beam structure", "Zen garden integration"],
    materials: ["Hinoki cypress", "Shoji paper", "Tatami", "Bamboo", "Kuromatsu pine"],
    famous: ["Katsura Imperial Villa", "Ise Grand Shrine", "Any Kyoto machiya"],
    dreamSeed: "A Japanese traditional home with hinoki cypress post-and-beam structure, shoji screens, tatami rooms, engawa porch overlooking a dry garden with moss and stone",
    costTier: "ultra",
    tags: ["japanese", "traditional", "zen", "garden", "spiritual"],
  },
  {
    id: "scandinavian-cabin",
    name: "Scandinavian Cabin",
    emoji: "🧊",
    era: "Viking–present",
    region: "Scandinavia",
    palette: ["#1A1A1A", "#F5F0E8", "#4A4A4A", "#C8D4B8"],
    tagline: "Black timber, white snow, and the Northern Lights",
    characteristics: ["Black-stained timber cladding", "Pitched roof with large overhang", "Triple-glazed panoramic windows", "Wood-burning sauna", "Radiant floor heating"],
    materials: ["Blackened pine", "White oak", "Stone", "Wool", "Reindeer hide"],
    famous: ["Any Norwegian hytte", "Cabin Vindheim by Vardehaugen", "Any Airbnb that went viral"],
    dreamSeed: "A Scandinavian cabin with black-stained timber exterior, pitched roof, triple-glazed forest-view windows, wood-burning sauna, radiant heated stone floors, and white oak interiors",
    costTier: "premium",
    tags: ["scandinavian", "cabin", "dark", "sauna", "forest", "hygge"],
  },
  // ─── LUXURY / STATEMENT ──────────────────────────────────
  {
    id: "ultra-modern",
    name: "Ultra Modern",
    emoji: "🔲",
    era: "2000s–present",
    region: "Global",
    palette: ["#FFFFFF", "#1A1A1A", "#C0C0C0", "#0A0A0A"],
    tagline: "Pure form, zero ornament, maximum drama",
    characteristics: ["Floating volumes", "Floor-to-ceiling glass on all sides", "Cantilevered sections", "Infinity pool flush with floor", "Hidden technology"],
    materials: ["Poured concrete", "Structural glass", "Steel", "Marble", "Mirror"],
    famous: ["Villa E by Bo Design", "Case Farmacostas by Alberto Campo Baeza", "Any Beverly Hills spec mansion"],
    dreamSeed: "An ultra modern home with floating white concrete volumes, full-height glass on all sides, cantilevered upper floor over infinity pool, seamless marble floors continuing outside",
    costTier: "ultra",
    tags: ["ultra-modern", "glass", "concrete", "statement", "luxury"],
  },
  {
    id: "glass-house",
    name: "Glass House",
    emoji: "🪟",
    era: "1950s–present",
    region: "Global",
    palette: ["#E8F0F8", "#2C2C2C", "#8B7355", "#4A6741"],
    tagline: "Live inside the landscape",
    characteristics: ["Full-perimeter glass walls", "Minimal steel structure", "Nature as the interior design", "Open plan", "Perfect geometry"],
    materials: ["Structural glass", "Steel I-beam", "Terrazzo", "Marble", "Minimal furniture"],
    famous: ["Glass House by Philip Johnson", "Farnsworth House by Mies van der Rohe", "Villa Tugendhat"],
    dreamSeed: "A glass house pavilion with floor-to-ceiling glass on all four sides, steel frame, terrazzo floors, and the forest as the only wallpaper — total transparency between inside and outside",
    costTier: "ultra",
    tags: ["glass", "minimalist", "nature", "transparent", "iconic"],
  },
  // ─── SPECIAL / NICHE ─────────────────────────────────────
  {
    id: "treehouse-modern",
    name: "Modern Treehouse",
    emoji: "🌳",
    era: "2000s–present",
    region: "Global",
    palette: ["#2C4A1A", "#8B7355", "#4A4A4A", "#C8B89A"],
    tagline: "Elevated above the world, rooted in it",
    characteristics: ["Built around or within trees", "Minimal site impact", "Elevated platforms and bridges", "Canopy-level living", "Natural ventilation"],
    materials: ["Cor-ten steel", "FSC timber", "Reclaimed wood", "Glass", "Polycarbonate"],
    famous: ["Yellow Treehouse Restaurant NZ", "Free Spirit Spheres", "Any Blue Forest treehouse"],
    dreamSeed: "A modern treehouse elevated 25 feet in the forest canopy, connected by rope bridges, with cantilevered deck, sleeping loft, and outdoor bathtub overlooking the forest floor",
    costTier: "premium",
    tags: ["treehouse", "nature", "unique", "elevated", "fantasy"],
  },
  {
    id: "earth-sheltered",
    name: "Earth-Sheltered",
    emoji: "🌍",
    era: "Ancient–present",
    region: "Global",
    palette: ["#4A7A2A", "#8B7355", "#C4B08A", "#2C2C2C"],
    tagline: "Grown from the earth, invisible from above",
    characteristics: ["Built into hillside or below grade", "Green roof with native plants", "South-facing glass wall", "Passive solar heating", "Extreme energy efficiency"],
    materials: ["Insulated concrete", "Green roof substrate", "Douglas fir", "Triple-pane glass", "Rammed earth"],
    famous: ["Malcolm Wells earth sheltered designs", "Hobbit houses in New Zealand", "Villa Vals Switzerland"],
    dreamSeed: "An earth-sheltered home built into a hillside with a green roof of wildflowers, south-facing floor-to-ceiling glass wall, passive solar design, and zero visible footprint from above",
    costTier: "premium",
    tags: ["sustainable", "earth", "green-roof", "passive-solar", "invisible"],
  },
  {
    id: "converted-warehouse",
    name: "Warehouse Conversion",
    emoji: "🏗️",
    era: "1980s–present",
    region: "Urban Global",
    palette: ["#4A4A4A", "#8B7355", "#FFFFFF", "#C8B89A"],
    tagline: "Industrial past, residential future",
    characteristics: ["Original structural bones preserved", "20–30 foot ceilings", "Sawtooth or skylights", "Raw vs refined contrast", "Mezzanine levels"],
    materials: ["Polished concrete", "Reclaimed brick", "Exposed steel", "Glass partitions", "White oak"],
    famous: ["Any Tribeca loft", "Tate Modern residences", "Clerkenwell loft conversions"],
    dreamSeed: "A converted warehouse home with original sawtooth roof skylights, polished concrete floors, exposed steel trusses, white-painted brick walls, floating mezzanine master suite",
    costTier: "premium",
    tags: ["industrial", "conversion", "urban", "loft", "high-ceiling"],
  },
  // ─── CONTEMPORARY INTERNATIONAL ──────────────────────────
  {
    id: "brazilian-tropical-modern",
    name: "Brazilian Tropical Modern",
    emoji: "🇧🇷",
    era: "1950s–present",
    region: "Brazil",
    palette: ["#4A7A2A", "#8B4513", "#C4A050", "#2C2C2C"],
    tagline: "Oscar Niemeyer meets the Amazon",
    characteristics: ["Pilotis (columns) lifting the structure", "Organic curving forms", "Tropical garden integration", "Natural cross-ventilation", "Outdoor life year-round"],
    materials: ["Concrete", "Azulejo tile", "Tropical hardwood", "Stone", "Exotic plants"],
    famous: ["Oscar Niemeyer residence", "Sítio Roberto Burle Marx", "Any São Paulo modernist villa"],
    dreamSeed: "A Brazilian tropical modern home elevated on pilotis, with curving concrete forms, azulejo tile, lush tropical garden, lap pool, and outdoor living room for year-round use",
    costTier: "premium",
    tags: ["tropical", "modern", "brazil", "organic", "outdoor"],
  },
  {
    id: "moroccan-riad",
    name: "Moroccan Riad",
    emoji: "🕌",
    era: "Ancient–present",
    region: "North Africa / Middle East",
    palette: ["#C4501A", "#D4A84B", "#4A2C8B", "#2C6B2C"],
    tagline: "Turn the city wall to the world, open paradise within",
    characteristics: ["Blank exterior wall to street", "Central courtyard with fountain", "Zellige tile everywhere", "Carved plasterwork", "Rooftop terrace"],
    materials: ["Zellige tile", "Tadelakt plaster", "Cedar wood carved screens", "Brass", "Terracotta"],
    famous: ["Palais Amani Fez", "Any medina riad", "Royal Mansour Marrakech"],
    dreamSeed: "A Moroccan riad with blank exterior, central courtyard with fountain and orange trees, hand-cut zellige tiles, tadelakt plaster bathrooms, carved cedar screens, and rooftop terrace with views",
    costTier: "premium",
    tags: ["moroccan", "courtyard", "tile", "exotic", "private"],
  },
  {
    id: "french-chateau",
    name: "French Château Style",
    emoji: "🏰",
    era: "1400s–present",
    region: "France",
    palette: ["#C8C0B0", "#4A4A4A", "#D4C8A0", "#2C3E2D"],
    tagline: "Stone walls, slate roofs, and centuries of secrets",
    characteristics: ["Mansard or steep slate roof", "Dormer windows", "Formal symmetry", "Stone façade", "Formal French garden"],
    materials: ["Limestone", "Slate", "Wrought iron", "Versailles parquet", "French limestone tile"],
    famous: ["Château de Villandry", "Any Loire Valley château", "Chenonceau"],
    dreamSeed: "A French château-style home with limestone façade, mansard slate roof, formal symmetrical composition, dormer windows, versailles parquet floors, and a formal parterre garden",
    costTier: "ultra",
    tags: ["french", "classic", "stone", "formal", "european"],
  },
  {
    id: "greek-island",
    name: "Greek Island Vernacular",
    emoji: "🏝️",
    era: "Ancient–present",
    region: "Greek Islands",
    palette: ["#FFFFFF", "#1B6CA8", "#D4A84B", "#4A7A4A"],
    tagline: "White plaster, blue domes, the Aegean always",
    characteristics: ["Whitewashed cubic volumes", "Blue-painted details", "Domed or flat roofs", "Organic stacked forms", "Sea view terraces"],
    materials: ["Whitewashed stucco", "Blue-painted iron", "Limestone", "Marble", "Ceramic tile"],
    famous: ["Oia, Santorini", "Any Cycladic architecture", "Amanzoe Resort"],
    dreamSeed: "A Cycladic-inspired home with whitewashed cubic volumes, blue dome and shutters, terraced outdoor living carved into the hillside, infinity pool, and sweeping sea views",
    costTier: "premium",
    tags: ["greek", "island", "white", "blue", "coastal", "mediterranean"],
  },
];

// ─── HELPER FUNCTIONS ────────────────────────────────────────────────────────

export function getStyleById(id: string): ArchStyle | undefined {
  return ARCHITECTURE_STYLES.find(s => s.id === id);
}

export function getStylesByTag(tag: string): ArchStyle[] {
  return ARCHITECTURE_STYLES.filter(s => s.tags.includes(tag));
}

export function getStylesByRegion(region: string): ArchStyle[] {
  const q = region.toLowerCase();
  return ARCHITECTURE_STYLES.filter(s => s.region.toLowerCase().includes(q));
}

export function getCostTierStyles(tier: ArchStyle["costTier"]): ArchStyle[] {
  return ARCHITECTURE_STYLES.filter(s => s.costTier === tier);
}

// Maps Browse & Pick category selections to relevant styles
export const CATEGORY_STYLE_MAP: Record<string, string[]> = {
  "Modern":         ["desert-modernist", "ultra-modern", "glass-house", "california-modern"],
  "Craftsman":      ["craftsman"],
  "Mediterranean":  ["mediterranean", "spanish-colonial", "tuscan-farmhouse", "greek-island"],
  "Industrial":     ["brooklyn-industrial", "converted-warehouse"],
  "Colonial":       ["spanish-colonial", "french-chateau"],
  "A-Frame":        ["scandinavian-cabin", "pacific-northwest-modern"],
  "Prairie":        ["mid-century-modern"],
  "Japanese":       ["japandi", "japanese-traditional"],
  "Scandinavian":   ["scandinavian-cabin", "japandi"],
  "Spanish colonial":["spanish-colonial"],
  "Tuscan":         ["tuscan-farmhouse", "mediterranean"],
  "Moroccan":       ["moroccan-riad"],
  "Tropical Balinese": ["tropical-balinese", "brazilian-tropical-modern"],
  "Mountain lodge": ["pacific-northwest-modern", "scandinavian-cabin"],
  "Greek island":   ["greek-island", "mediterranean"],
};

// Expanded Surprise Me concepts — 9 across building types and styles
export const SURPRISE_CONCEPTS_EXPANDED = [
  // Row 1: Residential
  {
    title: "Desert Modernist Retreat",
    vibe: "Frank Lloyd Wright meets Joshua Tree. Low-slung concrete and glass dissolving into the red rock. Rooftop stargazing deck. Plunge pool. The landscape is the interior design.",
    style: "desert-modernist", sqft: 3200, type: "residential",
    color: "#C4501A",
  },
  {
    title: "Japandi Forest House",
    vibe: "Wabi-sabi meets hygge in a cedar clearing. White oak floors, engawa porch, outdoor soaking tub. Every morning feels like a meditation retreat.",
    style: "japandi", sqft: 2400, type: "residential",
    color: "#8B8070",
  },
  {
    title: "Brooklyn Industrial Loft",
    vibe: "A 10,000 sq ft warehouse reinvented. 20-foot ceilings, original sawtooth skylights, chef's kitchen with concrete island. A mezzanine master suite above the living room.",
    style: "brooklyn-industrial", sqft: 4800, type: "residential",
    color: "#4A4A4A",
  },
  // Row 2: Exotic / Statement
  {
    title: "Balinese Jungle Villa",
    vibe: "Open-air pavilions connected by stone paths through tropical gardens. Infinity pool vanishing into the jungle. No air conditioning needed — just the breeze.",
    style: "tropical-balinese", sqft: 5500, type: "residential",
    color: "#2C4A2C",
  },
  {
    title: "Greek Island Compound",
    vibe: "Whitewashed cubic volumes stacked down a cliff face. Blue domes, sea view terraces at every level, a cave pool carved into the rock, and the Aegean always.",
    style: "greek-island", sqft: 4000, type: "residential",
    color: "#1B6CA8",
  },
  {
    title: "Moroccan Riad",
    vibe: "Blank walls to the street. Inside: a world of zellige tile, carved plaster, citrus trees, and a fountain. A rooftop terrace above the medina. Total privacy, total beauty.",
    style: "moroccan-riad", sqft: 3800, type: "residential",
    color: "#C4501A",
  },
  // Row 3: Unusual / Bold
  {
    title: "Earth-Sheltered Hillside Home",
    vibe: "Built into the hillside. Invisible from above — just wildflowers and sky. South-facing glass wall floods the house with light. Zero energy bills. Zero visual footprint.",
    style: "earth-sheltered", sqft: 2800, type: "residential",
    color: "#4A7A2A",
  },
  {
    title: "Glass House Pavilion",
    vibe: "Four walls of glass in a meadow. The forest is the wallpaper, the sky is the ceiling. A single structure of steel and transparency. You live inside the landscape.",
    style: "glass-house", sqft: 2200, type: "residential",
    color: "#1A1A2E",
  },
  {
    title: "Converted Tuscan Farmhouse",
    vibe: "800-year-old stone walls. 21st-century kitchen. Chestnut beams original to the 1400s. A wine cellar carved by monks. Olive grove. Pizza oven. Stars like you've never seen.",
    style: "tuscan-farmhouse", sqft: 6000, type: "residential",
    color: "#D4A84B",
  },
];
