// Batch 3: push from 438 to 500+
const SUPABASE_URL = "https://vlezoyalutexenbnzzui.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXpveWFsdXRleGVuYm56enVpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE3NTkwMSwiZXhwIjoyMDg3NzUxOTAxfQ.0-gT1eeuLwCK4khGkuh8g6Srzz6LcuzIcyGrGFXfyOk";
async function post(rows) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/knowledge_entities?on_conflict=slug`, {
    method: "POST", headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, "Content-Type": "application/json", Prefer: "return=minimal,resolution=merge-duplicates" },
    body: JSON.stringify(rows),
  });
  if (!res.ok) { console.error(`ERROR ${res.status}: ${(await res.text()).slice(0,200)}`); return false; }
  return true;
}
function e(slug, title, summary, type, tags, meta = {}) {
  return { slug, title:{en:title}, summary:{en:summary}, body:{en:""}, entity_type:type, domain:"construction", status:"published", tags, metadata:meta, source_urls:[] };
}

const IRC_CODES = [
  e("irc-r303","IRC R303 — Light, Ventilation, Heating","Habitable rooms require natural light (8% floor area glazing) or artificial lighting, natural ventilation (4% floor area openable) or mechanical ventilation, and heating to maintain 68°F at 3 ft above floor.","building_code",["IRC","residential","ventilation","lighting","heating"],{code_body:"IRC",code_year:2024,section:"R303",category:"IRC — Interior"}),
  e("irc-r310","IRC R310 — Emergency Escape","Emergency escape and rescue opening requirements for sleeping rooms and basements: minimum 5.7 sf net clear opening, minimum 20\" wide, 24\" high, max 44\" sill height. Window wells for below-grade.","building_code",["IRC","egress","window","bedroom","basement"],{code_body:"IRC",code_year:2024,section:"R310",category:"IRC — Egress"}),
  e("irc-r312","IRC R312 — Guards and Window Fall Prevention","Guards required at 30\" above grade: 36\" minimum height. Opening limitations (4\" sphere rule). Window fall prevention for windows >72\" above grade in children's spaces (6 and under).","building_code",["IRC","guards","railing","window","fall-prevention"],{code_body:"IRC",code_year:2024,section:"R312",category:"IRC — Guards"}),
  e("irc-r313","IRC R313 — Automatic Fire Sprinklers","Requires NFPA 13D automatic fire sprinkler systems in new one- and two-family dwellings and townhouses. Coverage extends to all habitable areas. Tied to domestic water supply. Controversial but increasingly adopted.","building_code",["IRC","fire-sprinkler","residential","NFPA-13D"],{code_body:"IRC",code_year:2024,section:"R313",category:"IRC — Fire Sprinkler"}),
  e("irc-r314","IRC R314 — Smoke Alarms","Smoke alarm requirements: every bedroom, outside bedrooms, each story, interconnected (hardwired with battery backup). Ionization or photoelectric. 10-year sealed battery alarms permitted.","building_code",["IRC","smoke-alarm","detector","bedroom","life-safety"],{code_body:"IRC",code_year:2024,section:"R314",category:"IRC — Smoke Alarms"}),
  e("irc-r315","IRC R315 — Carbon Monoxide Alarms","CO alarm required outside sleeping areas on every level with fuel-burning appliances, fireplaces, or attached garages. New construction and alterations triggering permits. Combined smoke/CO units permitted.","building_code",["IRC","carbon-monoxide","CO-alarm","gas","detector"],{code_body:"IRC",code_year:2024,section:"R315",category:"IRC — CO Alarms"}),
  e("irc-r403","IRC R403 — Footings","Foundation footing requirements: minimum 12\" wide for 1-story, 15\" for 2-story, 18\" for 3-story. Minimum depth below undisturbed ground. Frost depth per Table R301.2. Reinforcement for seismic and high-wind zones.","building_code",["IRC","footing","foundation","frost-depth","residential"],{code_body:"IRC",code_year:2024,section:"R403",category:"IRC — Foundations"}),
  e("irc-r404","IRC R404 — Foundation Walls","Foundation wall design for concrete, masonry, wood, and precast. Includes lateral soil pressure tables, minimum thickness, waterproofing/dampproofing requirements, and insect termite protection.","building_code",["IRC","foundation-wall","concrete","masonry","waterproofing"],{code_body:"IRC",code_year:2024,section:"R404",category:"IRC — Foundation Walls"}),
  e("irc-r502","IRC R502 — Wood Floor Framing","Floor joist span tables based on species, grade, spacing, and dead/live loads. Drilling/notching limits (max D/3 notch, D/3 hole). Bearing requirements, bridging, and subfloor fastening schedules.","building_code",["IRC","floor","joist","span-table","framing"],{code_body:"IRC",code_year:2024,section:"R502",category:"IRC — Floor Framing"}),
  e("irc-r505","IRC R505 — Cold-Formed Steel Floor Framing","CFS floor framing requirements including member sizes, spans, web stiffeners, clip angles, bridging, and connection details. References AISI S230 for prescriptive design.","building_code",["IRC","CFS","steel","floor","framing"],{code_body:"IRC",code_year:2024,section:"R505",category:"IRC — Steel Floors"}),
  e("irc-r702","IRC R702 — Interior Covering","Interior wall and ceiling covering requirements including gypsum board installation (fastener spacing, joint treatment), cement board for wet areas, wood paneling, and fire-rated assemblies for garage separations.","building_code",["IRC","drywall","gypsum","interior","garage-separation"],{code_body:"IRC",code_year:2024,section:"R702",category:"IRC — Interior"}),
  e("irc-r703","IRC R703 — Exterior Covering","Exterior wall covering and weather-resistive barrier requirements. WRB behind all cladding except masonry veneer. Flashing at windows, doors, and penetrations. Cladding attachment, weep screeds, kick-out flashing.","building_code",["IRC","exterior","siding","WRB","flashing","cladding"],{code_body:"IRC",code_year:2024,section:"R703",category:"IRC — Exterior"}),
  e("irc-r905","IRC R905 — Roof Covering","Roofing material requirements by type: asphalt shingles (ASTM D3462), metal, tile, slate, wood shakes. Underlayment requirements, ice barrier in cold climates, fire classification, wind resistance.","building_code",["IRC","roofing","shingles","metal","underlayment"],{code_body:"IRC",code_year:2024,section:"R905",category:"IRC — Roofing"}),
  e("irc-e3601","IRC E3601 — Residential Electrical Services","Residential electrical service requirements: minimum 100A for existing, 200A for new construction. Service entrance conductor sizing, service disconnect location, grounding electrode system, and meter base.","building_code",["IRC","electrical","service","200A","grounding"],{code_body:"IRC",code_year:2024,section:"E3601",category:"IRC — Electrical"}),
  e("irc-p2603","IRC P2603 — Residential Plumbing","Residential plumbing general provisions including pipe support spacing, protection from physical damage, pipe penetrations through framing, trenching and backfill requirements, and freeze protection.","building_code",["IRC","plumbing","pipe","residential","protection"],{code_body:"IRC",code_year:2024,section:"P2603",category:"IRC — Plumbing"}),
];

const NFPA_STANDARDS = [
  e("standard-nfpa-13","NFPA 13 — Automatic Sprinkler Systems","Standard for installation of sprinkler systems in commercial/industrial buildings. Covers system types (wet, dry, preaction, deluge), design density, pipe sizing, hydraulic calculations, and component specs.","standard",["NFPA","sprinkler","fire-suppression","commercial","hydraulic"],{standard_body:"NFPA",number:"13-2022",category:"Fire — Sprinkler"}),
  e("standard-nfpa-13d","NFPA 13D — Residential Sprinklers","Standard for sprinkler systems in one- and two-family dwellings and manufactured homes. Simplified design from NFPA 13. Domestic water supply typically adequate. Referenced by IRC R313.","standard",["NFPA","sprinkler","residential","IRC","domestic-water"],{standard_body:"NFPA",number:"13D-2022",category:"Fire — Residential Sprinkler"}),
  e("standard-nfpa-70e","NFPA 70E — Electrical Safety in the Workplace","Standard for electrical safety practices including arc flash hazard analysis, shock risk assessment, PPE requirements, energized work permits, and lockout/tagout procedures for maintenance.","standard",["NFPA","electrical","arc-flash","safety","PPE"],{standard_body:"NFPA",number:"70E-2024",category:"Electrical Safety"}),
  e("standard-nfpa-72","NFPA 72 — Fire Alarm and Signaling","National fire alarm and signaling code covering system design, installation, and testing of fire alarm, emergency communication, mass notification, and carbon monoxide detection systems.","standard",["NFPA","fire-alarm","detection","notification","signaling"],{standard_body:"NFPA",number:"72-2022",category:"Fire — Alarm"}),
  e("standard-nfpa-101","NFPA 101 — Life Safety Code","Comprehensive life safety code covering means of egress, fire protection features, building services, and operating features. Alternative to IBC egress provisions. Mandatory for CMS healthcare facilities.","standard",["NFPA","life-safety","egress","healthcare","fire"],{standard_body:"NFPA",number:"101-2024",category:"Life Safety"}),
  e("standard-nfpa-25","NFPA 25 — Inspection/Testing/Maintenance of Water-Based Systems","Standard for ITM of sprinkler systems, standpipe, fire pump, water storage, and water spray systems. Quarterly, annual, and 5-year inspection frequencies. Required for fire protection system maintenance.","standard",["NFPA","inspection","sprinkler","maintenance","fire-pump"],{standard_body:"NFPA",number:"25-2023",category:"Fire — Maintenance"}),
  e("standard-nfpa-70","NFPA 70 (NEC) — National Electrical Code","The comprehensive standard for electrical installation in the United States. Covers wiring, equipment, and installations for all voltages. Published triennially (2023 current). Adopted by reference in IBC Chapter 27.","standard",["NFPA","NEC","electrical","wiring","national"],{standard_body:"NFPA",number:"70-2023",category:"Electrical"}),
  e("standard-asce-7","ASCE 7 — Minimum Design Loads","Standard defining dead loads, live loads, snow loads, rain loads, wind loads, and seismic forces for building design. Referenced by IBC Chapter 16. Includes risk categories, importance factors, and load combinations.","standard",["ASCE","loads","wind","seismic","structural"],{standard_body:"ASCE",number:"7-22",category:"Structural — Loads"}),
  e("standard-icc-a117","ICC A117.1 — Accessible Design","Standard for accessible and usable buildings and facilities. Referenced by IBC Chapter 11. Covers accessible routes, parking, ramps, doors, toilets, kitchens, signage, and communication features. Aligns with ADA requirements.","standard",["ICC","accessibility","ADA","design","disability"],{standard_body:"ICC",number:"A117.1-2017",category:"Accessibility"}),
];

const MORE_METHODS = [
  e("method-soil-nailing","Soil Nailing","Ground stabilization method inserting steel bars (nails) into excavation face, then covering with shotcrete. Used for temporary and permanent retaining walls in top-down excavation. Faster and cheaper than soldier pile/lagging for suitable soils.","method",["excavation","retaining-wall","soil","stabilization","shotcrete"],{productivity:"200-500 sf face/day",typical_depth:"Up to 60 ft",cost_per_sf_face:"$25-$50",category:"Geotechnical"}),
  e("method-micropile","Micropile Foundation","Small-diameter (4-12 inch) drilled and grouted pile for foundation support in limited access, low headroom, and difficult soil conditions. Carries 50-500 kip loads. Used for underpinning, seismic retrofit, and new construction on problematic soils.","method",["foundation","micropile","underpinning","deep-foundation","grouted"],{diameter:"4-12 inches",capacity:"50-500 kips",installation:"Drilling rig + grout pump",category:"Foundations — Deep"}),
  e("method-spray-fireproofing","Spray-Applied Fireproofing (SFRM)","Spray-applied fire-resistive material (cite: mineral fiber or cementitious) applied to structural steel for fire resistance ratings (1-4 hours). Thickness per UL assembly listing. Must pass bond/cohesion tests. Inspected before concealment.","method",["fireproofing","steel","SFRM","fire-rating","spray"],{types:"Cementitious, Mineral Fiber",thickness:"1/2 to 2+ inches per rating",cost_per_sf:"$2-$6",category:"Fire Protection"}),
  e("method-mass-timber","Mass Timber Construction (CLT/Glulam)","Heavy timber construction using engineered wood products: Cross-Laminated Timber (CLT) panels for floors/walls/roofs, Glued-Laminated Timber (glulam) for beams/columns. IBC Type IV-A/B/C. Fire-resistant through charring. Carbon-sequestering.","method",["mass-timber","CLT","glulam","Type-IV","carbon"],{max_height:"18 stories (IBC Type IV-A)",fire_behavior:"Self-extinguishing char layer",carbon:"Sequesters ~1 ton CO2 per m³",category:"Structure — Mass Timber"}),
  e("method-modular-construction","Modular Construction","Volumetric 3D modules built in factory, transported to site, and assembled with crane. 30-50% faster than site-built. Quality controlled environment. Modules: 12-16 ft wide (road limits), up to 75 ft long. Steel or wood frame.","method",["modular","prefab","factory","volumetric","off-site"],{time_savings:"30-50% vs site-built",module_width:"12-16 ft (road limit)",max_height:"Varies by jurisdiction",category:"Off-Site Construction"}),
  e("method-bim-coordination","BIM Clash Detection / MEP Coordination","3D model-based coordination process to identify and resolve spatial conflicts between structural, mechanical, electrical, plumbing, and fire protection systems before construction. Software: Navisworks, Solibri, BIMcollab.","method",["BIM","coordination","clash-detection","MEP","3D-model"],{software:"Navisworks, Solibri, BIMcollab",typical_savings:"$10-$30 per sf in avoided RFIs",phase:"DESIGN/PLAN",category:"Technology — BIM"}),
  e("method-concrete-scanning","Ground-Penetrating Radar (GPR) / Concrete Scanning","Non-destructive testing to locate rebar, post-tension cables, conduits, and voids in concrete before cutting or coring. GPR units: GSSI, Hilti PS 1000, Proceq GP8000. Required before any concrete penetration.","method",["GPR","scanning","concrete","non-destructive","testing"],{equipment:"GSSI, Hilti PS 1000, Proceq",depth:"Up to 24 inches in concrete",cost:"$500-$2,000 per scan area",category:"Testing — Non-Destructive"}),
];

const MORE_BTYPES = [
  e("btype-senior-living","Senior Living / Assisted Living Facility","Residential care facility for elderly with varying levels of assistance. I-1 or I-2 occupancy per IBC. Requires accessible design throughout, fire sprinklers, emergency call systems, and dietary services. Growing market with aging population.","building_type",["senior-living","assisted","healthcare","accessible","residential-care"],{typical_cost_per_sf:"$250-$500",key_codes:"IBC, NFPA 101, ADA/FHA, state licensing",occupancy:"I-1 or I-2",category:"Healthcare"}),
  e("btype-parking-garage","Parking Structure","Multi-level vehicle parking facility: cast-in-place concrete, precast, or steel frame. Open (natural ventilation) or enclosed (mechanical ventilation + CO monitoring). Post-tensioned slabs common. Corrosion protection critical in northern climates.","building_type",["parking","garage","concrete","post-tension","structure"],{typical_cost_per_sf:"$60-$120",construction_types:"Cast-in-place, precast double-tee, steel",key_considerations:"Drainage, lighting, ventilation, corrosion protection",category:"Infrastructure"}),
  e("btype-restaurant","Restaurant / Food Service","Commercial kitchen and dining establishment. Complex MEP: Type I hood and fire suppression (NFPA 96), grease trap, makeup air, A/C for dining, walk-in cooler/freezer. Health department approval. ADA accessible.","building_type",["restaurant","kitchen","food-service","hood","grease-trap"],{typical_cost_per_sf:"$250-$600 (buildout)",key_codes:"IBC, NFPA 96, health code, ADA",mep_complexity:"High — hood, fire suppression, grease, HVAC",category:"Commercial — Food"}),
  e("btype-self-storage","Self-Storage Facility","Climate-controlled or non-climate storage units. Steel or concrete tilt-up construction. Simple MEP. High ROI for developers. Fire protection required. Security systems, access control, and lighting critical.","building_type",["self-storage","warehouse","steel","investment","simple"],{typical_cost_per_sf:"$40-$80 (climate-controlled $60-$120)",construction:"Steel frame, CMU, tilt-up",key_considerations:"Fire separation, security, climate control",category:"Commercial — Storage"}),
  e("btype-worship","House of Worship / Religious Assembly","Assembly occupancy (A-3) for religious services. Often complex architecture with large open spans, tall ceilings, acoustic requirements, and stained glass. ADA accessible. May include classrooms, commercial kitchen, childcare.","building_type",["church","worship","assembly","acoustic","religious"],{typical_cost_per_sf:"$200-$500",occupancy:"A-3 Assembly",key_considerations:"Acoustics, large spans, accessibility, fire egress",category:"Assembly"}),
  e("btype-laboratory","Laboratory / Research Facility","Specialized building for scientific research with precise environmental controls. BSL-1 through BSL-4 containment levels. Chemical fume hoods, biosafety cabinets, high air change rates (6-20 ACH), emergency showers, and specialized waste handling.","building_type",["laboratory","research","BSL","fume-hood","containment"],{typical_cost_per_sf:"$500-$1,500",air_changes:"6-20 ACH",key_codes:"IBC, NFPA 45, ANSI Z9.5, CDC/NIH BMBL",category:"Institutional — Lab"}),
  e("btype-hotel","Hotel / Hospitality","Multi-story lodging facility with guest rooms, lobby, back-of-house, and amenity spaces. R-1 occupancy. Fire sprinklers required. Acoustic separation between rooms. Complex MEP with individual room PTAC/VRF systems.","building_type",["hotel","hospitality","lodging","guest-room","R-1"],{typical_cost_per_sf:"$200-$600",occupancy:"R-1 Residential",key_systems:"PTAC/VRF, fire alarm, access control, laundry",category:"Hospitality"}),
  e("btype-school","K-12 School","Educational facility for children ages 5-18. E occupancy. Strict code requirements for egress, fire safety, security, and accessibility. HVAC critical for IAQ (ASHRAE 62.1). Increasingly includes hardened entries and safe rooms.","building_type",["school","educational","K-12","classroom","E-occupancy"],{typical_cost_per_sf:"$300-$600",occupancy:"E Educational",key_codes:"IBC, ASHRAE 62.1, state education dept",category:"Institutional — Education"}),
];

const FINAL_MATERIALS = [
  e("material-stucco","Traditional Stucco (3-Coat)","Portland cement plaster exterior finish: scratch coat, brown coat, finish coat over metal lath and WRB. Total thickness ~7/8\". Durable, fire-resistant, breathable. Requires control joints at 144 sf max panels.","material",["stucco","plaster","exterior","cement","lath"],{csi_division:"09",thickness:"7/8 inch total",cost_per_sf:"$7-$12 installed",sustainability_grade:"B"}),
  e("material-eifs","EIFS (Exterior Insulation Finish System)","Synthetic stucco system: adhesive/mechanical attachment, EPS foam insulation board, base coat with mesh, finish coat. Provides continuous insulation. Moisture-managed (drainable) systems required for most applications.","material",["EIFS","exterior","insulation","synthetic-stucco","drainable"],{csi_division:"07",r_value:"R-4 per inch (EPS)",cost_per_sf:"$8-$15 installed",sustainability_grade:"B"}),
  e("material-structural-screws","Structural Screws (Simpson SDS/SDWH)","Engineered structural fasteners replacing through-bolts and lag screws in wood-to-wood connections. ICC-ES evaluated. Simpson Strong-Tie SDS, SDWH, SDWC series. No pre-drilling required in most applications. Published load tables.","material",["fastener","structural","Simpson","screw","connection"],{csi_division:"06",brands:"Simpson SDS, SDWH, SDWC, GRK",cost_each:"$0.50-$3.00",advantages:"No pre-drill, high shear/withdrawal",sustainability_grade:"C"}),
  e("material-geomembrane","HDPE Geomembrane Liner","High-density polyethylene sheet liner for containment, landfills, ponds, and below-slab vapor barriers. 40-100 mil thickness. Heat-welded seams. Chemical resistant. Used for stormwater detention, decorative ponds, and environmental containment.","material",["geomembrane","HDPE","liner","containment","vapor-barrier"],{csi_division:"07",thickness:"40-100 mil",cost_per_sf:"$0.50-$2.00",sustainability_grade:"C"}),
  e("material-brick-veneer","Brick Veneer (Modular)","Non-structural clay brick cladding tied to backup wall with corrugated ties. Standard modular: 3-5/8 x 2-1/4 x 7-5/8 inches. Requires 1\" air space, weep holes, flashing at base and shelf angles. 100+ year expected life.","material",["brick","veneer","masonry","cladding","clay"],{csi_division:"04",size:"3-5/8 x 2-1/4 x 7-5/8 (modular)",cost_per_sf:"$12-$25 installed",lifespan:"100+ years",sustainability_grade:"B"}),
  e("material-glass-curtainwall","Low-E Insulated Glass Unit (IGU)","Double or triple-pane insulated glass with low-emissivity coating for energy performance. U-factor 0.25-0.35 (double), 0.15-0.22 (triple). SHGC 0.25-0.40. Argon or krypton gas fill between panes.","material",["glass","IGU","low-E","window","curtain-wall"],{csi_division:"08",u_factor:"0.25-0.35 (double pane)",shgc:"0.25-0.40",cost_per_sf:"$25-$60",sustainability_grade:"A"}),
  e("material-lvt","Luxury Vinyl Tile (LVT)","Multi-layer resilient flooring: wear layer, printed design layer, rigid core (SPC/WPC), and backing. Waterproof, durable, easy installation (click-lock). Commercial-grade: 20+ mil wear layer. Residential: 6-20 mil.","material",["flooring","LVT","vinyl","waterproof","resilient"],{csi_division:"09",wear_layers:"6-28 mil",cost_per_sf:"$3-$8 installed",warranty:"15-lifetime",sustainability_grade:"C"}),
  e("material-carpet-tile","Carpet Tile (Modular)","24x24 or 18x36 inch carpet squares with backing. Easy replacement of damaged tiles. Common in offices and commercial spaces. Interface, Shaw, Mohawk brands. Recyclable backing available. Low VOC options.","material",["flooring","carpet","tile","commercial","modular"],{csi_division:"09",sizes:"24x24, 18x36 inches",cost_per_sf:"$2-$6 material",sustainability_grade:"B"}),
  e("material-ductile-iron","Ductile Iron Pipe","Iron pipe for water mains, fire hydrant laterals, and large-diameter water distribution. Sizes 3\" to 64\". Push-on or mechanical joint connections. Cement-lined interior. Polyethylene encasement in corrosive soils.","material",["pipe","ductile-iron","water-main","fire-hydrant","underground"],{csi_division:"33",standard:"AWWA C151",sizes:"3 to 64 inches",cost_per_lf:"$8-$80 (varies by size)",sustainability_grade:"B"}),
  e("material-precast-hollow-core","Precast Hollow-Core Plank","Factory-produced prestressed concrete floor/roof planks with hollow cores for weight reduction. Depths: 6-16 inches. Spans up to 40 ft. Efficient for parking garages, multi-story residential, and commercial buildings.","material",["precast","hollow-core","concrete","plank","floor"],{csi_division:"03",depths:"6, 8, 10, 12, 16 inches",span:"Up to 40 ft",cost_per_sf:"$15-$30 installed",sustainability_grade:"C"}),
];

const FINAL_SAFETY = [
  e("safety-asbestos","Asbestos Management (EPA/OSHA)","Requirements for identifying, managing, and removing asbestos-containing materials in renovation and demolition. NESHAP notification, accredited inspectors, licensed abatement contractors, air monitoring, and proper disposal.","safety_regulation",["asbestos","abatement","EPA","NESHAP","demolition"],{regulation_body:"EPA/OSHA",section:"40 CFR 61 Subpart M / 1926.1101",jurisdiction:"us",category:"Hazmat — Asbestos"}),
  e("safety-lead-paint","Lead Paint (EPA RRP Rule)","EPA Renovation, Repair, and Painting Rule for pre-1978 buildings. Certified renovator required. Lead-safe work practices, containment, HEPA vacuum, prohibited methods (open flame, dry scraping). Consumer notification.","safety_regulation",["lead","paint","EPA","RRP","renovation"],{regulation_body:"EPA",section:"40 CFR 745 Subpart E",jurisdiction:"us",trigger:"Pre-1978 buildings",category:"Hazmat — Lead"}),
  e("safety-steel-erection","Steel Erection Safety (OSHA 1926 Subpart R)","Steel erection specific safety requirements: site layout, hoisting and rigging, structural stability during erection, column anchorage, beams and columns, open web steel joists, systems-engineered metal buildings, and fall protection at 15 ft.","safety_regulation",["OSHA","steel","erection","fall-protection","rigging"],{regulation_body:"OSHA",section:"1926 Subpart R",jurisdiction:"us",fall_trigger:"15 feet",category:"Steel Erection"}),
  e("safety-scaffolding","Scaffolding Safety (OSHA 1926 Subpart L)","Scaffold erection, use, and dismantling requirements. Supported and suspended scaffolds. Capacity: 4x intended load. Guardrails at 10 ft+. Competent person for erection/inspection. Planking requirements. Fall protection.","safety_regulation",["OSHA","scaffold","fall-protection","erection","guardrail"],{regulation_body:"OSHA",section:"1926 Subpart L",jurisdiction:"us",guardrail_trigger:"10 feet",category:"Scaffolding"}),
  e("safety-electrical-work","Electrical Safety (OSHA 1926 Subpart K)","Construction electrical safety covering assured equipment grounding conductor program (or GFCI), clearances from power lines, working near energized parts, and lockout/tagout for electrical equipment maintenance.","safety_regulation",["OSHA","electrical","GFCI","power-lines","grounding"],{regulation_body:"OSHA",section:"1926 Subpart K",jurisdiction:"us",category:"Electrical Safety"}),
];

const FINAL_SEQUENCES = [
  e("seq-foundation","Foundation Construction Sequence","Foundation sequence: 1) Excavation to bearing, 2) Verify soil bearing (geotechnical), 3) Form footings, 4) Pre-pour inspection, 5) Place footing concrete, 6) Strip forms after cure, 7) Foundation walls, 8) Waterproofing/dampproofing, 9) Drainage, 10) Backfill.","sequence_rule",["foundation","footing","excavation","concrete","sequence"],{phase:"BUILD",predecessor:"Site work + survey complete",successor:"Slab or framing",critical_holds:["Soil verification","Pre-pour inspection","Waterproofing inspection"],category:"Structure — Foundation"}),
  e("seq-rough-mep","MEP Rough-In Sequence","Mechanical/electrical/plumbing rough-in order: 1) Underground plumbing, 2) Slab pour, 3) Wall framing, 4) Plumbing rough (top-out), 5) HVAC ductwork, 6) Electrical rough, 7) Low-voltage/data, 8) Fire sprinkler, 9) Insulation, 10) Inspections before close-in.","sequence_rule",["MEP","rough-in","plumbing","electrical","HVAC"],{phase:"BUILD",predecessor:"Framing + sheathing complete",successor:"Insulation → drywall",critical_holds:["Underground plumbing inspection","MEP rough-in inspection"],category:"MEP — Rough-In"}),
  e("seq-exterior-envelope","Building Envelope Sequence","Envelope installation order: 1) Structural sheathing, 2) WRB/air barrier, 3) Window/door rough openings flashed, 4) Windows installed, 5) Continuous insulation (if required), 6) Cladding support, 7) Cladding installation, 8) Penetration sealing, 9) Testing.","sequence_rule",["envelope","WRB","window","cladding","air-barrier"],{phase:"BUILD",predecessor:"Framing + roof dried in",successor:"Interior finishes",weather_dependency:"WRB before rain exposure",critical_holds:["WRB inspection","Window flashing inspection"],category:"Envelope"}),
  e("seq-closeout","Project Closeout Sequence","Closeout sequence: 1) Substantial completion punch list, 2) Final inspections (building, fire, health), 3) Certificate of Occupancy, 4) Owner training on systems, 5) As-built documents, 6) Warranty packages, 7) Final payment, 8) Lien waivers, 9) Project archive.","sequence_rule",["closeout","punch-list","CO","warranty","inspection"],{phase:"DELIVER",predecessor:"All work complete + final cleaning",successor:"Occupancy + warranty period",critical_holds:["Final building inspection","Fire marshal inspection","CO issued"],category:"Closeout"}),
  e("seq-concrete-slab","Concrete Slab-on-Grade Sequence","Slab construction: 1) Sub-grade compaction (95% Proctor), 2) Vapor barrier (10-15 mil), 3) Gravel base (4-6 in), 4) Edge forms, 5) Rebar/mesh placement on chairs, 6) Pre-pour inspection, 7) Concrete placement, 8) Finishing (screed, float, trowel), 9) Curing (7+ days).","sequence_rule",["concrete","slab","vapor-barrier","compaction","finishing"],{phase:"BUILD",predecessor:"Underground MEP complete",successor:"Framing or interior work",cure_time:"7 days minimum before loading",critical_holds:["Pre-pour inspection","Compaction test"],category:"Concrete — Slab"}),
  e("seq-elevator-install","Elevator Installation Sequence","Elevator sequence: 1) Hoistway complete (plumb, square), 2) Machine room ready, 3) Guide rails installed, 4) Controller and wiring, 5) Car assembly, 6) Door operators, 7) Safety devices, 8) Adjustments, 9) Load test, 10) State inspection and certification.","sequence_rule",["elevator","hoistway","installation","certification","vertical"],{phase:"BUILD",predecessor:"Structure complete through top floor",successor:"Final inspections + CO",duration:"8-16 weeks (hydraulic), 12-24 weeks (traction)",critical_holds:["Hoistway plumb verification","State elevator inspection"],category:"Vertical Transport"}),
];

// ═══ EXECUTION ═══
async function main() {
  const batches = [
    { name: "IRC Residential (15)", data: IRC_CODES },
    { name: "NFPA Standards (9)", data: NFPA_STANDARDS },
    { name: "More Methods (7)", data: MORE_METHODS },
    { name: "More Building Types (8)", data: MORE_BTYPES },
    { name: "More Materials (10)", data: FINAL_MATERIALS },
    { name: "More Safety (5)", data: FINAL_SAFETY },
    { name: "More Sequences (6)", data: FINAL_SEQUENCES },
  ];
  let total = 0;
  for (const b of batches) {
    process.stdout.write(`Posting ${b.name}...`);
    if (await post(b.data)) { total += b.data.length; console.log(` ✓ (${total})`); }
    else console.log(` FAILED`);
  }
  const res = await fetch(`${SUPABASE_URL}/rest/v1/knowledge_entities?select=entity_type&status=eq.published`, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  const data = await res.json();
  const c = {}; data.forEach(e => c[e.entity_type] = (c[e.entity_type]||0)+1);
  console.log(`\nPosted ${total}. Total: ${data.length}`);
  Object.entries(c).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>console.log(`  ${k}: ${v}`));
}
main().catch(console.error);
