// Batch 2: push from 387 toward 500
const SUPABASE_URL = "https://vlezoyalutexenbnzzui.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXpveWFsdXRleGVuYm56enVpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjE3NTkwMSwiZXhwIjoyMDg3NzUxOTAxfQ.0-gT1eeuLwCK4khGkuh8g6Srzz6LcuzIcyGrGFXfyOk";

async function post(rows) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/knowledge_entities?on_conflict=slug`, {
    method: "POST",
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}`, "Content-Type": "application/json", Prefer: "return=minimal,resolution=merge-duplicates" },
    body: JSON.stringify(rows),
  });
  if (!res.ok) { const t = await res.text(); console.error(`ERROR ${res.status}: ${t.slice(0,200)}`); return false; }
  return true;
}

function e(slug, title, summary, type, tags, metadata = {}) {
  return { slug, title: { en: title }, summary: { en: summary }, body: { en: "" },
    entity_type: type, domain: "construction", status: "published", tags, metadata, source_urls: [] };
}

const IBC_REMAINING = [
  e("ibc-chapter-1","IBC Chapter 1 — Scope & Administration","Administrative provisions including scope, applicability, permits, inspections, certificate of occupancy, board of appeals, violations, and fees. Foundation chapter defining how the IBC is applied and enforced.","building_code",["IBC","administration","permits","scope"],{code_body:"IBC",code_year:2024,section:"Chapter 1",category:"IBC — Admin"}),
  e("ibc-chapter-2","IBC Chapter 2 — Definitions","Definitions of terms used throughout the IBC including construction types, occupancy groups, fire resistance, accessibility, structural, and MEP terminology. Critical for consistent code interpretation.","building_code",["IBC","definitions","terminology"],{code_body:"IBC",code_year:2024,section:"Chapter 2",category:"IBC — Definitions"}),
  e("ibc-chapter-4","IBC Chapter 4 — Special Detailed Requirements","Requirements for special occupancies and uses: covered malls, high-rise buildings, atriums, underground buildings, motor vehicle facilities, hazardous materials, ambulatory care, and live/work units.","building_code",["IBC","high-rise","atrium","hazardous","special-occupancy"],{code_body:"IBC",code_year:2024,section:"Chapter 4",category:"IBC — Special Uses"}),
  e("ibc-chapter-5","IBC Chapter 5 — General Building Heights & Areas","Allowable building heights and areas based on construction type and occupancy. Table 504.3/504.4 for height limits, Table 506.2 for area limits. Includes frontage and sprinkler increases.","building_code",["IBC","height","area","construction-type","frontage"],{code_body:"IBC",code_year:2024,section:"Chapter 5",category:"IBC — Height & Area"}),
  e("ibc-chapter-6","IBC Chapter 6 — Types of Construction","Five construction types (I-A through V-B) defined by fire resistance ratings of structural elements. Table 601 specifies required fire resistance for building elements based on construction type.","building_code",["IBC","construction-type","fire-resistance","Type-I","Type-V"],{code_body:"IBC",code_year:2024,section:"Chapter 6",category:"IBC — Construction Types"}),
  e("ibc-chapter-8","IBC Chapter 8 — Interior Finishes","Requirements for interior wall/ceiling finishes and floor finishes. Flame spread index (ASTM E84) and smoke developed index classifications. Class A/B/C ratings based on location and sprinkler status.","building_code",["IBC","interior-finish","flame-spread","smoke","ASTM-E84"],{code_body:"IBC",code_year:2024,section:"Chapter 8",category:"IBC — Finishes"}),
  e("ibc-chapter-10","IBC Chapter 10 — Means of Egress","Complete egress requirements: occupant load calculations, exit access, exit and exit discharge, exit signs, emergency lighting, stairways, corridors, doors, accessible means of egress, and assembly seating.","building_code",["IBC","egress","exit","occupant-load","stairway","corridor"],{code_body:"IBC",code_year:2024,section:"Chapter 10",category:"IBC — Egress"}),
  e("ibc-chapter-11","IBC Chapter 11 — Accessibility","Accessibility requirements referencing ICC A117.1 standard. Scoping provisions for accessible routes, parking, entrances, toilet rooms, signage, and dwelling units. Compliance with ADA through code.","building_code",["IBC","accessibility","ADA","ICC-A117","parking"],{code_body:"IBC",code_year:2024,section:"Chapter 11",category:"IBC — Accessibility"}),
  e("ibc-chapter-12","IBC Chapter 12 — Interior Environment","Requirements for ventilation, lighting, temperature control, sound transmission, and room dimensions. Natural and mechanical ventilation. Minimum ceiling heights and room areas.","building_code",["IBC","ventilation","lighting","sound","interior"],{code_body:"IBC",code_year:2024,section:"Chapter 12",category:"IBC — Interior"}),
  e("ibc-chapter-13","IBC Chapter 13 — Energy Efficiency","Energy conservation requirements referencing IECC. Compliance paths: prescriptive, performance, and Energy Rating Index. Applies to building envelope, HVAC, lighting, and water heating.","building_code",["IBC","energy","IECC","envelope","efficiency"],{code_body:"IBC",code_year:2024,section:"Chapter 13",category:"IBC — Energy"}),
  e("ibc-chapter-14","IBC Chapter 14 — Exterior Walls","Exterior wall covering requirements including weather resistance, water-resistive barriers, flashing, cladding attachment, exterior insulation, and veneers (masonry, stone, metal, wood, stucco).","building_code",["IBC","exterior-wall","cladding","WRB","flashing"],{code_body:"IBC",code_year:2024,section:"Chapter 14",category:"IBC — Exterior Walls"}),
  e("ibc-chapter-15","IBC Chapter 15 — Roof Assemblies","Roofing requirements covering materials, fire classification (A/B/C), wind resistance, impact resistance, insulation, roof drainage, reroofing, and photovoltaic panel installation on roofs.","building_code",["IBC","roofing","fire-classification","wind","drainage"],{code_body:"IBC",code_year:2024,section:"Chapter 15",category:"IBC — Roofing"}),
  e("ibc-chapter-16","IBC Chapter 16 — Structural Design","Structural design requirements including dead loads, live loads, snow loads, wind loads, seismic forces (ASCE 7 reference), soil lateral loads, flood loads, and load combinations (LRFD and ASD).","building_code",["IBC","structural","loads","seismic","ASCE-7","wind"],{code_body:"IBC",code_year:2024,section:"Chapter 16",category:"IBC — Structural"}),
  e("ibc-chapter-17","IBC Chapter 17 — Special Inspections & Testing","Requirements for special inspections during construction including structural steel, concrete, masonry, soils, sprayed fire-resistive materials, and smoke control. Specifies who can perform inspections.","building_code",["IBC","special-inspection","testing","quality","structural"],{code_body:"IBC",code_year:2024,section:"Chapter 17",category:"IBC — Inspections"}),
  e("ibc-chapter-18","IBC Chapter 18 — Soils and Foundations","Foundation and soils requirements: geotechnical investigations, allowable bearing pressures, shallow foundations (spread footings), deep foundations (piles, piers), retaining walls, and dampproofing/waterproofing.","building_code",["IBC","foundation","soils","piles","waterproofing"],{code_body:"IBC",code_year:2024,section:"Chapter 18",category:"IBC — Foundations"}),
  e("ibc-chapter-19","IBC Chapter 19 — Concrete","Structural concrete requirements referencing ACI 318. Covers reinforced concrete, prestressed concrete, precast, plain concrete, shotcrete, and gypsum concrete. Includes fire resistance provisions.","building_code",["IBC","concrete","ACI-318","reinforcement","structural"],{code_body:"IBC",code_year:2024,section:"Chapter 19",category:"IBC — Concrete"}),
  e("ibc-chapter-22","IBC Chapter 22 — Steel","Structural steel requirements referencing AISC 360 for hot-rolled, AISI for cold-formed, SJI for steel joists, and SDI for steel deck. Includes composite construction and light-frame steel.","building_code",["IBC","steel","AISC","cold-formed","composite"],{code_body:"IBC",code_year:2024,section:"Chapter 22",category:"IBC — Steel"}),
  e("ibc-chapter-23","IBC Chapter 23 — Wood","Wood construction requirements referencing AWC NDS for design, IRC for conventional framing, and AITC for glulam. Covers sawn lumber, engineered wood, CLT, and preservative-treated wood.","building_code",["IBC","wood","lumber","CLT","engineered-wood","NDS"],{code_body:"IBC",code_year:2024,section:"Chapter 23",category:"IBC — Wood"}),
  e("ibc-chapter-24","IBC Chapter 24 — Glass and Glazing","Safety glazing requirements, wind load resistance, human impact (CPSC 16 CFR 1201), sloped glazing, skylights, glass guards, and fire-rated glazing assemblies.","building_code",["IBC","glass","glazing","safety-glass","skylight"],{code_body:"IBC",code_year:2024,section:"Chapter 24",category:"IBC — Glass"}),
  e("ibc-chapter-25","IBC Chapter 25 — Gypsum Board and Plaster","Requirements for gypsum board, gypsum plaster, and exterior stucco including installation, fire resistance, moisture resistance, and weather exposure ratings.","building_code",["IBC","gypsum","drywall","plaster","stucco"],{code_body:"IBC",code_year:2024,section:"Chapter 25",category:"IBC — Gypsum"}),
  e("ibc-chapter-26","IBC Chapter 26 — Plastic","Plastic materials in building construction including foam plastic insulation, light-transmitting plastics (skylights, signs), fiber-reinforced polymer, and plastic composites. Fire safety provisions.","building_code",["IBC","plastic","foam","insulation","skylight"],{code_body:"IBC",code_year:2024,section:"Chapter 26",category:"IBC — Plastics"}),
  e("ibc-chapter-27","IBC Chapter 27 — Electrical","Electrical requirements referencing NFPA 70 (NEC) for all electrical installations. Covers power, lighting, communications, and fire alarm system electrical connections.","building_code",["IBC","electrical","NEC","NFPA-70","wiring"],{code_body:"IBC",code_year:2024,section:"Chapter 27",category:"IBC — Electrical"}),
  e("ibc-chapter-28","IBC Chapter 28 — Mechanical Systems","Mechanical system requirements referencing IMC for HVAC, ventilation, exhaust, duct systems, and combustion air. Includes chimneys and fireplaces.","building_code",["IBC","mechanical","HVAC","IMC","ductwork"],{code_body:"IBC",code_year:2024,section:"Chapter 28",category:"IBC — Mechanical"}),
  e("ibc-chapter-29","IBC Chapter 29 — Plumbing Systems","Plumbing requirements referencing IPC for fixtures, water supply, DWV systems, and storm drainage. Includes minimum fixture counts per Table 2902.1 based on occupancy.","building_code",["IBC","plumbing","IPC","fixtures","drainage"],{code_body:"IBC",code_year:2024,section:"Chapter 29",category:"IBC — Plumbing"}),
  e("ibc-chapter-30","IBC Chapter 30 — Elevators","Elevator and conveying system requirements referencing ASME A17.1. Covers traction, hydraulic, and machine-room-less elevators, escalators, platform lifts, and emergency operation.","building_code",["IBC","elevator","ASME","escalator","conveying"],{code_body:"IBC",code_year:2024,section:"Chapter 30",category:"IBC — Elevators"}),
  e("ibc-chapter-33","IBC Chapter 33 — Safeguards During Construction","Safety requirements during construction including pedestrian protection, fire extinguishers, standpipes, means of egress, protection of adjacent properties, and fire watch requirements.","building_code",["IBC","construction-safety","temporary","fire-watch","protection"],{code_body:"IBC",code_year:2024,section:"Chapter 33",category:"IBC — Construction Safety"}),
];

const MORE_MATERIALS = [
  e("material-fiberglass-batt","Fiberglass Batt Insulation","Most common residential insulation. R-3.2 per inch for standard density, R-3.8 for high-density. Unfaced, kraft-faced, or foil-faced. Sizes: 15\" and 23\" widths for 16\" and 24\" o.c. framing. Non-combustible.","material",["insulation","fiberglass","batt","residential","R-value"],{csi_division:"07",r_value_per_inch:"R-3.2 to R-3.8",cost_per_sf:"$0.30-$0.80",fire_rating:"Non-combustible",sustainability_grade:"B"}),
  e("material-cellulose-insulation","Cellulose Insulation (Blown-In)","Recycled paper fiber insulation blown into wall cavities and attics. R-3.5 per inch. Treated with borates for fire/pest resistance. Dense-pack (3.5 lb/ft³) or loose-fill (1.5 lb/ft³). High recycled content.","material",["insulation","cellulose","blown-in","recycled","attic"],{csi_division:"07",r_value_per_inch:"R-3.5",density:"1.5-3.5 lb/ft³",cost_per_sf:"$0.40-$0.90",sustainability_grade:"A"}),
  e("material-lvl-beam","LVL (Laminated Veneer Lumber)","Engineered wood product made from thin wood veneers laminated with adhesive. Higher strength and stiffness than sawn lumber. Used for beams, headers, and rim boards. Common depths: 7.25\" to 18\". Consistent properties.","material",["engineered-wood","LVL","beam","header","structural"],{csi_division:"06",allowable_bending:"2,600 psi",MOE:"1.9M psi",cost_per_lf:"$3-$12 (varies by depth)",sustainability_grade:"B"}),
  e("material-tji-joist","TJI (I-Joist)","Engineered wood I-shaped floor joist with OSB or plywood web and LVL or sawn lumber flanges. Spans up to 32 ft. Depths: 9.5\" to 16\". Lighter than sawn lumber, no crowning needed. Requires web stiffeners at bearing points.","material",["engineered-wood","I-joist","floor","TJI","structural"],{csi_division:"06",span_capability:"Up to 32 ft",depths:"9.5, 11.875, 14, 16 inches",cost_per_lf:"$2-$6",sustainability_grade:"B"}),
  e("material-pex-a","PEX-A Tubing","Cross-linked polyethylene tubing (Engel method) for potable water and radiant heating. Most flexible PEX type. Expansion fittings maintain full-bore flow. Sizes 3/8\" to 1\". Max 200°F, 160 psi. Red (hot), blue (cold), white (either).","material",["PEX","plumbing","water","radiant","tubing"],{csi_division:"22",standard:"ASTM F876/F877",max_temp:"200°F",max_pressure:"160 psi",cost_per_lf:"$0.50-$2.00",sustainability_grade:"B"}),
  e("material-hdpe-pipe","HDPE Pipe","High-density polyethylene pipe for water mains, storm drainage, sewer force mains, and geothermal loops. Fused joints (no leaks). Flexible, corrosion-proof. DR ratings: DR11 (160 psi) to DR32.5 (50 psi). Sizes 1/2\" to 65\".","material",["HDPE","pipe","water-main","storm","geothermal"],{csi_division:"22",standard:"ASTM D3350/D3035",cost_per_lf:"$2-$25 (varies by size)",sustainability_grade:"B"}),
  e("material-structural-concrete-6000","Concrete 6000 PSI","High-strength concrete at 6,000 psi (41.4 MPa). Used for columns, post-tensioned slabs, precast, and high-rise structural elements. Often requires supplementary cementitious materials (fly ash, silica fume). Careful curing critical.","material",["concrete","high-strength","structural","column","precast"],{csi_division:"03",compressive_strength:"6,000 psi",cure_time:"28 days",cost_per_cy:"$170-$220",sustainability_grade:"D"}),
  e("material-fiber-cement-siding","Fiber Cement Siding (Hardie)","Cement, cellulose fiber, and sand composite siding. Non-combustible, rot-proof, termite-proof. Lap, panel, and shingle profiles. Primed or pre-finished. 50-year warranty. James Hardie dominant brand (HardiePlank).","material",["siding","fiber-cement","Hardie","exterior","cladding"],{csi_division:"07",fire_rating:"Non-combustible",warranty:"30-50 years",cost_per_sf:"$5-$12 installed",sustainability_grade:"B"}),
  e("material-standing-seam-metal","Standing Seam Metal Roof (24ga)","Concealed-fastener metal roofing with raised seams. 24-gauge steel or 0.032\" aluminum. Kynar/PVDF finish. Panel widths: 12\", 16\", 18\". Thermal movement accommodated by clip design. 40-60 year expected life.","material",["roofing","metal","standing-seam","steel","aluminum"],{csi_division:"07",gauges:"24ga steel, 0.032 aluminum",cost_per_sf:"$8-$16 installed",warranty:"40+ years paint, lifetime substrate",sustainability_grade:"A"}),
  e("material-quartzite-countertop","Quartzite Countertop","Natural metamorphic stone countertop. Harder than granite (7 on Mohs scale). Heat resistant, scratch resistant. Requires periodic sealing. Colors: white, gray, blue, green with veining. Premium natural stone option.","material",["countertop","quartzite","stone","kitchen","natural"],{csi_division:"12",hardness:"7 Mohs",cost_per_sf:"$70-$200 installed",maintenance:"Annual sealing",sustainability_grade:"C"}),
  e("material-quartz-countertop","Engineered Quartz Countertop","Manufactured from 90-94% natural quartz with polymer resin binder. Non-porous, no sealing required. Consistent color and pattern. Brands: Caesarstone, Cambria, Silestone. Not heat resistant above 300°F.","material",["countertop","quartz","engineered","kitchen","bathroom"],{csi_division:"12",composition:"90-94% quartz + resin",cost_per_sf:"$50-$150 installed",maintenance:"No sealing needed",sustainability_grade:"C"}),
  e("material-architectural-concrete","Architectural Concrete (Exposed)","Decorative concrete with exposed aggregate, form liner patterns, or integral color. Requires high-quality formwork, careful mix design, consistent placement, and specialized finishing. Used for facades, retaining walls, and feature elements.","material",["concrete","architectural","exposed","decorative","facade"],{csi_division:"03",finish_types:"Exposed aggregate, form-lined, colored, polished",cost_per_sf:"$15-$40 (formwork + finish)",sustainability_grade:"C"}),
];

const MORE_TRADES = [
  e("trade-concrete-finisher","Concrete Finisher","Specializes in placing, leveling, and finishing concrete flatwork including slabs, sidewalks, driveways, and decorative concrete. Skills: screeding, bull floating, power troweling, brooming, stamping, and coloring. Critical timing for finish quality.","trade",["concrete","flatwork","finishing","trowel","stamping"],{apprenticeship:"2-3 years",median_wage:"$40,000-$65,000",certifications:"ACI Flatwork Finisher",category:"Concrete"}),
  e("trade-fire-sprinkler-fitter","Fire Sprinkler Fitter","Installs automatic fire sprinkler systems per NFPA 13/13R/13D. Calculates hydraulic requirements, sizes pipe, installs heads per coverage requirements. Separate trade from plumber in most jurisdictions. NICET certification valued.","trade",["fire-sprinkler","NFPA-13","suppression","pipe","life-safety"],{apprenticeship:"4-5 years",median_wage:"$55,000-$85,000",certifications:"NICET, OSHA, state license",category:"Fire Protection"}),
  e("trade-elevator-mechanic","Elevator Mechanic (Constructor)","Installs, maintains, and repairs elevators, escalators, and moving walkways. Highest-paid construction trade. Complex electrical, mechanical, and digital control systems. NEIEP 4-year apprenticeship. Strong union representation.","trade",["elevator","escalator","ASME","vertical-transport"],{apprenticeship:"4 years (NEIEP)",median_wage:"$80,000-$110,000",certifications:"State license, ASME A17.1",category:"Vertical Transport"}),
  e("trade-waterproofer","Waterproofer","Applies waterproofing and dampproofing systems to foundations, below-grade walls, plazas, tunnels, and water features. Methods: sheet membrane, fluid-applied, cementitious, bentonite clay, crystalline. Critical for below-grade integrity.","trade",["waterproofing","membrane","below-grade","foundation"],{apprenticeship:"3 years",median_wage:"$45,000-$70,000",certifications:"Manufacturer certifications",category:"Specialty — Waterproofing"}),
  e("trade-solar-installer","Solar PV Installer","Installs photovoltaic systems on rooftops and ground-mounted arrays. Combines electrical work (NEC 690), roofing, and structural attachment. NABCEP certification is industry standard. Growing rapidly with IRA incentives.","trade",["solar","photovoltaic","renewable","NEC-690","installer"],{certifications:"NABCEP PV Installation Professional",median_wage:"$45,000-$65,000",growth:"22% projected (2022-2032)",category:"Renewable Energy"}),
];

const MORE_CLIMATE = [
  e("climate-zone-1","IECC Climate Zone 1 — Very Hot-Humid","Warmest US climate zone including Hawaii, south Florida, south Texas, Puerto Rico, and US Virgin Islands. Cooling-dominated. Code focus: window SHGC limits, cool roofs, duct sealing, and vapor retarder placement (exterior side).","climate_zone",["IECC","hot-humid","cooling","Florida","Hawaii"],{iecc_zone:"1",hdd_range:"<2,000",cooling_focus:"Primary",example_cities:"Miami, Honolulu, Key West, San Juan",wall_insulation:"R-13 or R-20ci",roof_insulation:"R-30 to R-49"}),
  e("climate-zone-2","IECC Climate Zone 2 — Hot","Hot climate covering Gulf Coast, south/central Texas, Arizona, parts of California. Significant cooling load with some heating. Code balances SHGC for solar gain control with envelope insulation.","climate_zone",["IECC","hot","Gulf-Coast","Arizona","Texas"],{iecc_zone:"2",hdd_range:"2,000-3,000",example_cities:"Houston, Phoenix, Austin, New Orleans, Jacksonville",wall_insulation:"R-13+R-5ci or R-20ci",roof_insulation:"R-38 to R-60"}),
  e("climate-zone-3","IECC Climate Zone 3 — Warm","Mixed climate zone spanning mid-South, California coast, and parts of Southwest. Both heating and cooling significant. Code addresses both solar gain control and insulation levels.","climate_zone",["IECC","warm","mixed","California","Southeast"],{iecc_zone:"3",hdd_range:"3,000-4,000",example_cities:"Los Angeles, Atlanta, Dallas, Memphis, Las Vegas, Raleigh",wall_insulation:"R-13+R-5ci or R-20+R-3ci",roof_insulation:"R-38 to R-60"}),
  e("climate-zone-6","IECC Climate Zone 6 — Cold","Cold northern climate covering northern states, Great Lakes, and northern New England. Heating-dominated with high insulation requirements. Air sealing critical — max 3 ACH50 per IECC.","climate_zone",["IECC","cold","northern","heating","air-sealing"],{iecc_zone:"6",hdd_range:"7,000-8,000",example_cities:"Minneapolis, Burlington VT, Duluth, Bangor ME",wall_insulation:"R-20+R-5ci or R-13+R-10ci",roof_insulation:"R-49 to R-60",air_tightness:"3 ACH50 max"}),
  e("climate-zone-7","IECC Climate Zone 7 — Very Cold","Severe cold climate covering Alaska interior, far northern Minnesota/Wisconsin/Maine. Extreme heating loads. Highest insulation and air sealing requirements. Triple-pane windows often justified.","climate_zone",["IECC","very-cold","Alaska","subarctic","extreme"],{iecc_zone:"7",hdd_range:"8,000-9,000",example_cities:"Fairbanks AK, International Falls MN",wall_insulation:"R-20+R-10ci or R-13+R-15ci",roof_insulation:"R-60",air_tightness:"3 ACH50 max"}),
];

const MORE_ZONING = [
  e("zoning-c1","Zoning C-1 — Neighborhood Commercial","Low-intensity commercial district allowing retail, restaurants, offices, and personal services. Typically 1-3 stories with moderate setbacks. Often required to maintain neighborhood scale and pedestrian orientation.","zoning_district",["zoning","commercial","retail","neighborhood","setback"],{typical_far:"1.0-2.0",max_height:"35-45 ft",uses:"Retail, restaurant, office, personal service",parking:"Per use type",category:"Commercial"}),
  e("zoning-m1","Zoning M-1 — Light Industrial","Light industrial/manufacturing district allowing warehouses, workshops, light manufacturing, flex space, and increasingly data centers. Higher noise and truck traffic tolerance. Often transitional between commercial and heavy industrial.","zoning_district",["zoning","industrial","warehouse","manufacturing","flex"],{typical_far:"1.0-2.5",max_height:"45-65 ft",uses:"Warehouse, light mfg, flex, data center",parking:"1 per 1,000 sf typical",category:"Industrial"}),
  e("zoning-pud","Zoning PUD — Planned Unit Development","Flexible zoning overlay allowing mixed uses, varied densities, and creative site planning in exchange for public amenities and design review. Common for master-planned communities and large mixed-use developments.","zoning_district",["zoning","PUD","mixed-use","planned","flexibility"],{typical_far:"Varies by agreement",uses:"Residential, commercial, open space — per plan",category:"Special"}),
  e("zoning-tod","Zoning TOD — Transit-Oriented Development","Higher-density zoning within 1/4-1/2 mile of transit stations. Reduced parking requirements, increased FAR, and pedestrian-oriented design. Growing in adoption as cities prioritize transit ridership and housing density.","zoning_district",["zoning","TOD","transit","density","housing"],{typical_far:"3.0-8.0",max_height:"65-200 ft",parking:"50-75% of standard",category:"Transit-Oriented"}),
];

// ═══ EXECUTION ═══
async function main() {
  const batches = [
    { name: "IBC Remaining Chapters (26)", data: IBC_REMAINING },
    { name: "More Materials (12)", data: MORE_MATERIALS },
    { name: "More Trades (5)", data: MORE_TRADES },
    { name: "More Climate Zones (5)", data: MORE_CLIMATE },
    { name: "More Zoning Districts (4)", data: MORE_ZONING },
  ];

  let total = 0;
  for (const batch of batches) {
    process.stdout.write(`Posting ${batch.name}...`);
    const ok = await post(batch.data);
    if (ok) {
      total += batch.data.length;
      console.log(` ✓ (${total} total)`);
    } else {
      console.log(` FAILED`);
    }
  }

  // Verify count
  const res = await fetch(`${SUPABASE_URL}/rest/v1/knowledge_entities?select=entity_type&status=eq.published`, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  const data = await res.json();
  const counts = {};
  data.forEach(e => counts[e.entity_type] = (counts[e.entity_type] || 0) + 1);
  console.log(`\nPosted ${total} new entities.`);
  console.log(`Total entities in DB: ${data.length}`);
  Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([k,v]) => console.log(`  ${k}: ${v}`));
}

main().catch(console.error);
