import { ResourceResult } from './types';

export const demoFixtures: ResourceResult[] = [
  // TOOLS (3 results)
  {
    id: 'hd-001-sds-max-bit',
    kind: 'tool',
    title: 'DeWalt SDS-Max 3/4" Carbide Drill Bit',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/DeWalt-SDS-Max-3-4-Bit',
    priceUsd: 24.99,
    priceDisplay: '$24.99',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 128 },
    snippet: 'SDS-max carbide core bit for hammer drills. Premium durability.',
  },
  {
    id: 'lowes-002-circular-saw',
    kind: 'tool',
    title: 'Makita 7-1/4" Circular Saw with Brake',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Makita-Circular-Saw',
    priceUsd: 89.99,
    priceDisplay: '$89.99',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 92 },
    snippet: 'Corded 15-amp circular saw. Fast blade brake, dust blower.',
  },
  {
    id: 'hd-003-hand-tools',
    kind: 'tool',
    title: 'Stanley 65-Piece Homeowner Tool Set',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Stanley-Tool-Set',
    priceUsd: 49.97,
    priceDisplay: '$49.97',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'ships 2-3 days',
    rating: { stars: 4.3, count: 210 },
    snippet: 'Complete homeowner set with hammer, wrenches, sockets, and bits.',
  },

  // EQUIPMENT (3 results)
  {
    id: 'ur-001-scissor-lift',
    kind: 'equipment',
    title: 'Scissor Lift 19ft Electric (Max 500 lb)',
    vendor: 'United Rentals',
    source: 'craigslist',
    url: 'https://www.unitedrentals.com/equipment/scissor-lifts',
    priceUsd: 75,
    priceDisplay: '$75/day',
    distance: { miles: 1.2, text: '1.2 mi away' },
    availability: 'available today',
    rating: { stars: 4.8, count: 34 },
    snippet: 'Electric scissor lift, 19ft platform. Fits through 34" doors.',
    tags: ['delivery', 'insurance included'],
  },
  {
    id: 'sunbelt-002-forklift',
    kind: 'equipment',
    title: 'Telehandler 35ft Reach 5000 lb Load',
    vendor: 'Sunbelt Rentals',
    source: 'craigslist',
    url: 'https://www.sunbeltrentals.com/equipment',
    priceUsd: 180,
    priceDisplay: '$180/day + driver',
    distance: { miles: 4.8, text: '4.8 mi away' },
    availability: 'ships 2-3 days',
    rating: { stars: 4.6, count: 47 },
    snippet: 'Telescopic boom handler. Delivery included in Napa Valley.',
  },
  {
    id: 'cl-003-bobcat',
    kind: 'equipment',
    title: 'Bobcat S570 Skid Steer with Operator',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa',
    priceUsd: 120,
    priceDisplay: '$120/hour',
    distance: { miles: 6.3, text: '6.3 mi away' },
    availability: 'available today',
    rating: { stars: 4.4, count: 12 },
    snippet: 'Compact skid steer with bucket and grapple attachments.',
    tags: ['operator included', 'licensed'],
  },

  // SUPPLIES (4 results)
  {
    id: 'hd-004-lumber',
    kind: 'supply',
    title: '2x4x8 Pressure-Treated Lumber (per piece)',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Lumber-2x4x8',
    priceUsd: 7.49,
    priceDisplay: '$7.49 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 340 },
    snippet: 'Southern yellow pine, pressure-treated for outdoor use.',
  },
  {
    id: 'lowes-005-drywall',
    kind: 'supply',
    title: 'USG Sheetrock 1/2" Drywall Sheet 4x8',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Drywall-Sheetrock',
    priceUsd: 14.98,
    priceDisplay: '$14.98 per sheet',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 156 },
    snippet: 'Standard weight drywall, 1/2" thickness for interior walls.',
  },
  {
    id: 'napa-yard-006-concrete',
    kind: 'supply',
    title: 'Ready-Mix Concrete 4000 PSI (per cubic yard)',
    vendor: 'Napa Ready-Mix Supply',
    source: 'other',
    url: 'https://napareadymix.local/concrete',
    priceUsd: 185,
    priceDisplay: '$185/yd³',
    distance: { miles: 5.2, text: '5.2 mi away' },
    availability: 'available today',
    rating: { stars: 4.9, count: 89 },
    snippet: 'Local ready-mix concrete supplier. Same-day delivery available.',
    tags: ['local', 'delivery available'],
  },
  {
    id: 'hd-007-roofing',
    kind: 'supply',
    title: 'Owens Corning Duration Shingles (per bundle)',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Roofing-Shingles',
    priceUsd: 34.99,
    priceDisplay: '$34.99 per bundle',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 201 },
    snippet: '30-year architectural shingles. Covers ~33 sq ft per bundle.',
  },

  // SUBCONTRACTORS (4 results)
  {
    id: 'angi-001-framing',
    kind: 'subcontractor',
    title: 'Sonoma Valley Framing Co. — Residential & Commercial',
    vendor: 'Angi',
    source: 'angi',
    url: 'https://www.angi.com/companylist/sonoma-framing',
    distance: { miles: 8.4, text: '8.4 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.9, count: 67 },
    snippet: 'Licensed, bonded, insured. 15 years experience framing.',
    tags: ['licensed', 'bonded', 'insured', 'background checked'],
  },
  {
    id: 'thumbtack-002-plumbing',
    kind: 'subcontractor',
    title: 'Napa Plumbing Solutions — 24/7 Emergency Service',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/plumbing',
    distance: { miles: 3.1, text: '3.1 mi away' },
    availability: 'available today',
    rating: { stars: 4.7, count: 124 },
    snippet: 'Full-service plumbing. Licensed master plumber on staff.',
    tags: ['licensed', 'bonded', '24/7 available'],
  },
  {
    id: 'yelp-003-electrical',
    kind: 'subcontractor',
    title: 'Vintage Electric — Residential & Commercial Rewiring',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/vintage-electric-napa',
    distance: { miles: 2.9, text: '2.9 mi away' },
    availability: 'available next week',
    rating: { stars: 4.8, count: 88 },
    snippet: 'Licensed electrician. Panel upgrades, new wiring, troubleshooting.',
    tags: ['licensed', 'bonded', 'insured'],
  },
  {
    id: 'thumbtack-004-roofing',
    kind: 'subcontractor',
    title: 'Napa Roofing & Gutters — Full Roof Replacement',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/roofing',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'available 1 week',
    rating: { stars: 4.6, count: 45 },
    snippet: 'Roof replacements, repairs, gutters, and maintenance.',
    tags: ['licensed', 'bonded', 'free estimates'],
  },

  // LABORERS (3 results)
  {
    id: 'cl-001-general-labor',
    kind: 'laborer',
    title: 'General Construction Labor — Available Tomorrow 7am',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa/gig',
    priceUsd: 20,
    priceDisplay: '$20/hr',
    distance: { miles: 1.8, text: '1.8 mi away' },
    availability: 'available tomorrow 7am',
    rating: { stars: 4.5, count: 6 },
    snippet: 'Reliable crew. Framing, demolition, cleanup experience.',
    tags: ['crew available', 'transportation provided'],
  },
  {
    id: 'thumbtack-002-day-labor',
    kind: 'laborer',
    title: 'Skilled Day Laborers — Carpentry & Masonry',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/labor',
    priceUsd: 28,
    priceDisplay: '$28/hr',
    distance: { miles: 2.5, text: '2.5 mi away' },
    availability: 'available same-day',
    rating: { stars: 4.7, count: 34 },
    snippet: 'Pre-screened laborers. Framing, concrete, demolition specialists.',
    tags: ['background checked', 'insured'],
  },
  {
    id: 'cl-003-site-cleanup',
    kind: 'laborer',
    title: 'Site Cleanup Crew — Debris Removal & Hauling',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa/gig',
    priceUsd: 450,
    priceDisplay: '$450/day',
    distance: { miles: 7.1, text: '7.1 mi away' },
    availability: 'available today',
    rating: { stars: 4.4, count: 18 },
    snippet: 'Full crew with truck. Demolition debris, yard waste removal.',
    tags: ['haul away included', '3-person team'],
  },

  // SERVICES (4 results)
  {
    id: 'yelp-001-inspection',
    kind: 'service',
    title: 'Bay Area Home Inspections — Comprehensive Reports',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/bay-area-home-inspections-napa',
    priceUsd: 425,
    priceDisplay: '$425 per inspection',
    distance: { miles: 3.8, text: '3.8 mi away' },
    availability: 'available next 3 days',
    rating: { stars: 4.9, count: 76 },
    snippet: 'Licensed inspector. Detailed reports with photos and video.',
    tags: ['licensed', 'certified', 'detailed reports'],
  },
  {
    id: 'google-maps-002-soil-testing',
    kind: 'service',
    title: 'Geotechnical Solutions Inc — Soil Analysis & Reports',
    vendor: 'Google Maps',
    source: 'google_maps',
    url: 'https://maps.google.com/geo-solutions-napa',
    priceUsd: 600,
    priceDisplay: '$600–$1,200',
    distance: { miles: 9.2, text: '9.2 mi away' },
    availability: 'available 1 week',
    rating: { stars: 4.8, count: 41 },
    snippet: 'Professional soil testing, compaction analysis, engineering reports.',
    tags: ['licensed engineers', 'insurance included'],
  },
  {
    id: 'thumbtack-003-permit-assistance',
    kind: 'service',
    title: 'Napa Building Permits & Compliance Services',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/permit-services',
    priceUsd: 350,
    priceDisplay: '$350 base + filing fees',
    distance: { miles: 2.0, text: '2.0 mi away' },
    availability: 'available immediately',
    rating: { stars: 4.7, count: 52 },
    snippet: 'Expedite permit approvals, handle city submissions, compliance checks.',
    tags: ['local expert', 'no surprise fees'],
  },
  {
    id: 'yelp-004-design',
    kind: 'service',
    title: 'Modern Build Studio — Architecture & Design Consulting',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/modern-build-studio-napa',
    priceUsd: 150,
    priceDisplay: '$150/hr',
    distance: { miles: 5.1, text: '5.1 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.9, count: 29 },
    snippet: 'Licensed architects. Design consultation, construction drawings.',
    tags: ['licensed architects', 'BIM certified'],
  },
];
