import { ResourceResult } from './types';

export const demoFixtures: ResourceResult[] = [
  // ============================================================================
  // TOOLS & HAND EQUIPMENT (10 fixtures)
  // ============================================================================
  {
    id: 'hd-001-sds-max-bit-3-4',
    kind: 'tool',
    title: 'DeWalt SDS-Max 3/4" Carbide Drill Bit',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/DeWalt-SDS-Max-3-4-Bit',
    priceUsd: 85.99,
    priceDisplay: '$85.99',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 128 },
    snippet: 'SDS-max carbide core bit for hammer drills. Premium durability for concrete.',
    reasoning: 'Stocked locally, 30min pickup window. Highest-rated 3/4" SDS-max bit in region.',
  },
  {
    id: 'lowes-002-sds-max-bit-1-inch',
    kind: 'tool',
    title: 'Bosch 1" SDS-Max Rotary Hammer Bit',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Bosch-SDS-Max-1-Inch',
    priceUsd: 110.49,
    priceDisplay: '$110.49',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 92 },
    snippet: 'Heavy-duty 1" SDS-max bit. Extreme concrete penetration performance.',
    reasoning: 'Best per-unit value for 1" bits in area. In stock today.',
  },
  {
    id: 'grainger-003-impact-driver',
    kind: 'tool',
    title: 'Makita 18V Impact Driver Kit XDT13Z',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Makita-Impact-Driver',
    priceUsd: 129.00,
    priceDisplay: '$129.00',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 203 },
    snippet: 'Ultra-compact cordless impact driver. Perfect for framing fasteners.',
    reasoning: 'Verified contractor favorite. 203 reviews averaging 4.8 stars.',
  },
  {
    id: 'hd-004-circular-saw-7-1-4',
    kind: 'tool',
    title: 'Makita 7-1/4" Circular Saw with Brake',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Makita-Circular-Saw',
    priceUsd: 89.99,
    priceDisplay: '$89.99',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 156 },
    snippet: 'Corded 15-amp circular saw. Fast blade brake, dust blower.',
    reasoning: 'Best local availability. 156 verified buyer reviews.',
  },
  {
    id: 'lowes-005-measuring-tape-25ft',
    kind: 'tool',
    title: 'Stanley FatMax 25\' Measuring Tape — Dual Graduation',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Stanley-FatMax-Tape',
    priceUsd: 24.98,
    priceDisplay: '$24.98',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 387 },
    snippet: 'Wide, 25-foot tape measure with dual markings. Locking mechanism.',
    reasoning: 'Cheapest in region. 387 reviews. Industry standard.',
  },
  {
    id: 'grainger-006-sawzall-blade-set',
    kind: 'tool',
    title: 'Milwaukee 49-77-1221 Sawzall Blade Assortment (15-piece)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Milwaukee-Blade-Set',
    priceUsd: 39.99,
    priceDisplay: '$39.99',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 178 },
    snippet: 'Mixed blade set for wood, drywall, and metal cutting.',
    reasoning: 'Industrial supplier. Pre-screened for pro quality.',
  },
  {
    id: 'hd-007-hand-tools-kit',
    kind: 'tool',
    title: 'Stanley 65-Piece Homeowner Tool Set',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Stanley-Tool-Set',
    priceUsd: 49.97,
    priceDisplay: '$49.97',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.3, count: 210 },
    snippet: 'Complete homeowner set. Hammer, wrenches, sockets, bits, drivers.',
    reasoning: 'Good starter kit. 210 customer reviews. Locally available.',
  },
  {
    id: 'lowes-008-level-4-foot',
    kind: 'tool',
    title: 'Lowe\'s Pro 4-Foot Box Level Aluminum',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Pro-Box-Level',
    priceUsd: 34.98,
    priceDisplay: '$34.98',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 267 },
    snippet: 'Aluminum box level, 4-foot span. Shock-absorbing base.',
    reasoning: 'Professional choice. 267 reviews at 4.8 stars.',
  },
  {
    id: 'grainger-009-drill-bit-set',
    kind: 'tool',
    title: 'DeWalt DWA1169 Titanium Pilot Point Drill Bit Set (99-piece)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/DeWalt-Drill-Bit-Set',
    priceUsd: 54.99,
    priceDisplay: '$54.99',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.9, count: 145 },
    snippet: 'Titanium-coated drill bit assortment. Includes wood, metal, masonry bits.',
    reasoning: '99-piece kit. Covers all common drilling tasks. Pro-rated.',
  },
  {
    id: 'hd-010-saw-blade-10-inch',
    kind: 'tool',
    title: 'Milwaukee M18 10" Miter Saw Blade Combo Pack',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Milwaukee-Blade-Combo',
    priceUsd: 76.49,
    priceDisplay: '$76.49',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 89 },
    snippet: 'Premium carbide-tipped miter saw blade. 3-blade combo.',
    reasoning: 'Stocked locally. Three blades (rip, cross, chop). Best local price.',
  },

  // ============================================================================
  // HEAVY EQUIPMENT RENTAL (10 fixtures)
  // ============================================================================
  {
    id: 'ur-001-scissor-lift-19ft',
    kind: 'equipment',
    title: 'Scissor Lift 19ft Electric (Max 500 lb)',
    vendor: 'United Rentals',
    source: 'craigslist',
    url: 'https://www.unitedrentals.com/equipment/scissor-lifts',
    priceUsd: 75,
    priceDisplay: '$75/day',
    distance: { miles: 1.2, text: '1.2 mi away' },
    availability: 'available today',
    rating: { stars: 4.8, count: 34 },
    snippet: 'Electric scissor lift, 19ft platform. Fits through 34" doors.',
    reasoning: 'Closest rental shop. Same-day availability. Insurance included.',
    tags: ['delivery', 'insurance included'],
  },
  {
    id: 'sunbelt-002-boom-lift-40ft',
    kind: 'equipment',
    title: 'Telescopic Boom Lift 40ft Reach 5000 lb Load',
    vendor: 'Sunbelt Rentals',
    source: 'craigslist',
    url: 'https://www.sunbeltrentals.com/equipment',
    priceUsd: 220,
    priceDisplay: '$220/day + delivery',
    distance: { miles: 4.8, text: '4.8 mi away' },
    availability: 'available tomorrow',
    rating: { stars: 4.6, count: 47 },
    snippet: 'Telescopic boom handler, 40ft reach. Great for tall buildings.',
    reasoning: 'Regional leader. Free delivery. 47 verified rentals.',
  },
  {
    id: 'cl-003-bobcat-s570',
    kind: 'equipment',
    title: 'Bobcat S570 Skid Steer with Operator',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa',
    priceUsd: 120,
    priceDisplay: '$120/hour',
    distance: { miles: 6.3, text: '6.3 mi away' },
    availability: 'available today',
    rating: { stars: 4.4, count: 12 },
    snippet: 'Compact skid steer with bucket and grapple attachments.',
    reasoning: 'Operator included. Licensed and insured. Quick deployment.',
    tags: ['operator included', 'licensed'],
  },
  {
    id: 'napa-rentals-004-concrete-mixer',
    kind: 'equipment',
    title: 'Concrete Mixer 5-Cubic Foot Electric',
    vendor: 'Napa Equipment Rentals',
    source: 'other',
    url: 'https://www.napaequipment.local/equipment',
    priceUsd: 35,
    priceDisplay: '$35/day',
    distance: { miles: 2.8, text: '2.8 mi away' },
    availability: 'available today',
    rating: { stars: 4.7, count: 78 },
    snippet: 'Electric concrete mixer. 5 cu ft drum. Includes stand.',
    reasoning: 'Very local. Lowest daily rate. Ready today.',
  },
  {
    id: 'united-005-skid-steer-s750',
    kind: 'equipment',
    title: 'Skid Steer S750 High-Flow Loader Package',
    vendor: 'United Rentals',
    source: 'craigslist',
    url: 'https://www.unitedrentals.com/equipment',
    priceUsd: 145,
    priceDisplay: '$145/day',
    distance: { miles: 1.2, text: '1.2 mi away' },
    availability: 'available today',
    rating: { stars: 4.7, count: 89 },
    snippet: 'High-flow skid steer loader. Multiple attachment options.',
    reasoning: 'Industry leader. Closest rental. Multiple attachment options available.',
  },
  {
    id: 'sunbelt-006-trencher-ditch-witch',
    kind: 'equipment',
    title: 'Walk-Behind Trencher Ditch Witch 1020',
    vendor: 'Sunbelt Rentals',
    source: 'craigslist',
    url: 'https://www.sunbeltrentals.com/equipment',
    priceUsd: 85,
    priceDisplay: '$85/day',
    distance: { miles: 4.8, text: '4.8 mi away' },
    availability: 'available 2-3 days',
    rating: { stars: 4.5, count: 34 },
    snippet: 'Walk-behind trencher. Maximum 6" depth. Gas-powered.',
    reasoning: 'Specialized equipment. Regional availability. 34 verified rentals.',
  },
  {
    id: 'cl-007-excavator-mini-1-5-ton',
    kind: 'equipment',
    title: 'Mini Excavator 1.5-Ton with Operator & Transport',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa',
    priceUsd: 95,
    priceDisplay: '$95/hour',
    distance: { miles: 7.5, text: '7.5 mi away' },
    availability: 'available today',
    rating: { stars: 4.3, count: 18 },
    snippet: 'Mini excavator with licensed operator. Includes transport to site.',
    reasoning: 'All-inclusive rate. Operator and transport covered.',
  },
  {
    id: 'napa-rentals-008-plate-compactor',
    kind: 'equipment',
    title: 'Vibratory Plate Compactor 5.5 HP',
    vendor: 'Napa Equipment Rentals',
    source: 'other',
    url: 'https://www.napaequipment.local/equipment',
    priceUsd: 28,
    priceDisplay: '$28/day',
    distance: { miles: 2.8, text: '2.8 mi away' },
    availability: 'available today',
    rating: { stars: 4.6, count: 52 },
    snippet: 'Gas-powered plate compactor. 5.5 HP Honda engine.',
    reasoning: 'Best daily rate. Very local. Same-day pickup available.',
  },
  {
    id: 'united-009-tower-light',
    kind: 'equipment',
    title: 'Portable Tower Light System 4x1000W',
    vendor: 'United Rentals',
    source: 'craigslist',
    url: 'https://www.unitedrentals.com/equipment',
    priceUsd: 42,
    priceDisplay: '$42/day',
    distance: { miles: 1.2, text: '1.2 mi away' },
    availability: 'available today',
    rating: { stars: 4.8, count: 156 },
    snippet: 'Portable lighting tower. 4 x 1000W halogen. Mobile base.',
    reasoning: 'Highest-rated lighting solution. Very close. 4000W total output.',
  },
  {
    id: 'sunbelt-010-chop-saw-14-inch',
    kind: 'equipment',
    title: 'Portable Abrasive Chop Saw 14" with Stand',
    vendor: 'Sunbelt Rentals',
    source: 'craigslist',
    url: 'https://www.sunbeltrentals.com/equipment',
    priceUsd: 22,
    priceDisplay: '$22/day',
    distance: { miles: 4.8, text: '4.8 mi away' },
    availability: 'available today',
    rating: { stars: 4.7, count: 41 },
    snippet: '14" abrasive chop saw. Cuts steel, rebar. Includes stand.',
    reasoning: 'Best daily rate for cutting equipment. Regional availability.',
  },

  // ============================================================================
  // LUMBER & FRAMING SUPPLIES (10 fixtures)
  // ============================================================================
  {
    id: 'hd-101-2x4-8ft-pressure-treated',
    kind: 'supply',
    title: '2x4x8 Pressure-Treated Lumber (per piece)',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Lumber-2x4x8',
    priceUsd: 7.49,
    priceDisplay: '$7.49 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 340 },
    snippet: 'Southern yellow pine, pressure-treated for outdoor use.',
    reasoning: 'Stocked locally, 30min pickup window. Standard framing lumber.',
  },
  {
    id: 'lowes-102-2x6-8ft-cedar',
    kind: 'supply',
    title: '2x6x8 Western Red Cedar Grade A',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Cedar-Lumber-2x6',
    priceUsd: 18.98,
    priceDisplay: '$18.98 each',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 89 },
    snippet: 'Premium western red cedar. Rot-resistant, beautiful finish.',
    reasoning: 'Best local price for premium cedar. Grade A clear.',
  },
  {
    id: 'hd-103-plywood-3-4-in-4x8',
    kind: 'supply',
    title: '3/4" CDX Plywood 4x8 Sheet',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Plywood-3-4-CDX',
    priceUsd: 42.98,
    priceDisplay: '$42.98 per sheet',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 267 },
    snippet: '3/4" CDX plywood. Excellent strength. Fast pickup.',
    reasoning: 'Very local stock. Best framing plywood price.',
  },
  {
    id: 'lowes-104-osb-7-16-in-4x8',
    kind: 'supply',
    title: '7/16" OSB Oriented Strand Board 4x8 Sheet',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/OSB-Sheathing',
    priceUsd: 18.49,
    priceDisplay: '$18.49 per sheet',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.4, count: 178 },
    snippet: '7/16" OSB sheathing. Economical, strong option.',
    reasoning: 'Cheapest sheathing option. In stock today. 178 reviews.',
  },
  {
    id: 'grainger-105-engineered-lvl-2x10',
    kind: 'supply',
    title: '2x10 Engineered Laminated Veneer Lumber (LVL)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/LVL-Beams',
    priceUsd: 28.99,
    priceDisplay: '$28.99 per piece',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 94 },
    snippet: 'High-strength engineered lumber. Straight, consistent sizing.',
    reasoning: 'Best for beam applications. Highest-rated LVL supplier.',
  },
  {
    id: 'hd-106-2x8-pressure-treated-16ft',
    kind: 'supply',
    title: '2x8x16 Pressure-Treated Beam (per piece)',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/PT-Beam-2x8x16',
    priceUsd: 21.47,
    priceDisplay: '$21.47 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 123 },
    snippet: 'Longer pressure-treated beam. Deck and framing use.',
    reasoning: 'Very local availability. Longer lumber pieces in stock.',
  },
  {
    id: 'lowes-107-plywood-1-2-in-cdx',
    kind: 'supply',
    title: '1/2" CDX Plywood 4x8 Sheet',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Plywood-1-2-CDX',
    priceUsd: 32.98,
    priceDisplay: '$32.98 per sheet',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 201 },
    snippet: '1/2" CDX plywood. Good strength-to-weight ratio.',
    reasoning: 'Perfect for interior walls. Standard grade. 201 reviews.',
  },
  {
    id: 'grainger-108-treated-4x4-post-10ft',
    kind: 'supply',
    title: '4x4 Pressure-Treated Post 10ft',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/PT-Post-4x4',
    priceUsd: 19.99,
    priceDisplay: '$19.99 each',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 67 },
    snippet: '4x4 pressure-treated post. Deck and structure support.',
    reasoning: 'Industrial supplier. Premium pressure-treating.',
  },
  {
    id: 'hd-109-stud-2x4-8ft-std',
    kind: 'supply',
    title: 'Standard Grade 2x4x8 Studs (per piece)',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Studs-2x4x8',
    priceUsd: 4.98,
    priceDisplay: '$4.98 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 412 },
    snippet: 'Standard grade studs. Economy framing option.',
    reasoning: 'Best bulk pricing. 412 reviews. Very local.',
  },

  // ============================================================================
  // PLUMBING SUPPLIES (10 fixtures)
  // ============================================================================
  {
    id: 'hd-201-pex-tubing-1-2-in',
    kind: 'supply',
    title: '1/2" PEX Tubing 100ft Coil',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/PEX-Tubing-1-2',
    priceUsd: 49.98,
    priceDisplay: '$49.98 per coil',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 234 },
    snippet: '1/2" PEX tubing, 100ft coil. Flexible, durable.',
    reasoning: 'Best local availability. Industry standard. 234 reviews.',
  },
  {
    id: 'lowes-202-copper-pipe-3-4-in',
    kind: 'supply',
    title: '3/4" Copper Pipe L Type 50ft Coil',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Copper-Pipe-3-4',
    priceUsd: 89.99,
    priceDisplay: '$89.99 per coil',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 167 },
    snippet: 'Type L copper pipe, 50ft coil. Premium durability.',
    reasoning: 'Premium copper. 50-foot ready-to-use coil. 4.8 rating.',
  },
  {
    id: 'grainger-203-pex-fittings-assortment',
    kind: 'supply',
    title: 'PEX Compression Fitting Assortment (50-piece)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/PEX-Fittings',
    priceUsd: 34.99,
    priceDisplay: '$34.99 per assortment',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 89 },
    snippet: '50-piece PEX compression fitting assortment.',
    reasoning: 'Industrial supply. All common sizes. Pre-screened quality.',
  },
  {
    id: 'hd-204-plumbing-fixture-set',
    kind: 'supply',
    title: 'Moen Faucet & Fixture Combo Package',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Moen-Fixture-Combo',
    priceUsd: 145.99,
    priceDisplay: '$145.99',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 112 },
    snippet: 'Moen kitchen & bath faucet set. Includes drain assembly.',
    reasoning: 'Stocked locally. Matched fixtures with drains.',
  },
  {
    id: 'lowes-205-toilet-flange',
    kind: 'supply',
    title: 'PVC Toilet Flange 3-inch w/Bolts',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Toilet-Flange',
    priceUsd: 12.98,
    priceDisplay: '$12.98',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 278 },
    snippet: 'PVC toilet flange 3-inch. Includes bolts and ring.',
    reasoning: 'Best price. 278 verified purchases. Standard part.',
  },
  {
    id: 'grainger-206-copper-fittings',
    kind: 'supply',
    title: 'Copper Sweat Fitting Assortment (1/2" & 3/4")',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Copper-Fittings',
    priceUsd: 26.99,
    priceDisplay: '$26.99 per assortment',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 134 },
    snippet: 'Copper sweat-fitting assortment for soldering.',
    reasoning: 'Industrial standard. Full range of connections.',
  },
  {
    id: 'hd-207-drain-trap-assembly',
    kind: 'supply',
    title: 'Plastic P-Trap Assembly 1-1/2"',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/P-Trap-Assembly',
    priceUsd: 8.49,
    priceDisplay: '$8.49',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 201 },
    snippet: 'Plastic P-trap 1.5-inch, chrome finish.',
    reasoning: 'Very local. Standard drain assembly. 201 reviews.',
  },
  {
    id: 'lowes-208-pvc-schedule-40',
    kind: 'supply',
    title: '2" PVC Schedule 40 Pipe 10ft Length',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/PVC-Schedule-40',
    priceUsd: 11.98,
    priceDisplay: '$11.98 per piece',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 189 },
    snippet: '2" Schedule 40 PVC for drainage and venting.',
    reasoning: 'Standard drainage pipe. 189 verified purchases.',
  },
  {
    id: 'grainger-209-angle-stop-valve',
    kind: 'supply',
    title: 'Angle Stop Shutoff Valve 1/2" Compression',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Angle-Stop',
    priceUsd: 9.99,
    priceDisplay: '$9.99 each',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 156 },
    snippet: 'Angle stop valve for fixture shutoff. 1/2" compression.',
    reasoning: 'Industrial supplier. High quality, trusted brand.',
  },

  // ============================================================================
  // ELECTRICAL SUPPLIES (10 fixtures)
  // ============================================================================
  {
    id: 'hd-301-romex-12-2-50ft',
    kind: 'supply',
    title: 'Southwire Romex 12-2 w/Ground 50ft',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Romex-12-2',
    priceUsd: 34.98,
    priceDisplay: '$34.98 per spool',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 267 },
    snippet: 'Romex 12-2 with ground. Household wiring standard.',
    reasoning: 'Stocked locally. Industry standard. 267 reviews.',
  },
  {
    id: 'lowes-302-conduit-1-2-in-10ft',
    kind: 'supply',
    title: '1/2" EMT Conduit 10ft Length',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Conduit-1-2-EMT',
    priceUsd: 8.98,
    priceDisplay: '$8.98 per piece',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 156 },
    snippet: '1/2" EMT conduit. Protective wire covering.',
    reasoning: 'Standard conduit. In stock. Best local price.',
  },
  {
    id: 'grainger-303-breaker-20amp-single',
    kind: 'supply',
    title: 'Square D 20A Single Pole Circuit Breaker',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Circuit-Breaker-20A',
    priceUsd: 18.99,
    priceDisplay: '$18.99 each',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 89 },
    snippet: 'Square D 20A single-pole circuit breaker.',
    reasoning: 'Industrial-grade breaker. Highest-rated supplier.',
  },
  {
    id: 'hd-304-outlet-15amp-duplex',
    kind: 'supply',
    title: 'Leviton Duplex Receptacle 15A 125V',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Duplex-Outlet-15A',
    priceUsd: 2.99,
    priceDisplay: '$2.99 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 412 },
    snippet: 'Standard duplex outlet 15A. Leviton brand.',
    reasoning: 'Very local. Budget-friendly. 412 reviews.',
  },
  {
    id: 'lowes-305-panel-breaker-box-100a',
    kind: 'supply',
    title: '100A Main Breaker Panel 24-Space',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Breaker-Panel-100A',
    priceUsd: 189.99,
    priceDisplay: '$189.99',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'ships 2-3 days',
    rating: { stars: 4.7, count: 78 },
    snippet: '100A main breaker panel with 24 circuit spaces.',
    reasoning: 'Standard panel size. 78 verified installations.',
  },
  {
    id: 'grainger-306-wire-nuts-assortment',
    kind: 'supply',
    title: 'Wire Nut Assortment Set (50-piece)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Wire-Nuts',
    priceUsd: 12.99,
    priceDisplay: '$12.99 per assortment',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 112 },
    snippet: '50-piece wire nut assortment for all wire gauges.',
    reasoning: 'Industrial standard. All common sizes.',
  },
  {
    id: 'hd-307-light-switch-toggle',
    kind: 'supply',
    title: 'Leviton Toggle Light Switch 15A',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Light-Switch-Toggle',
    priceUsd: 3.49,
    priceDisplay: '$3.49 each',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 334 },
    snippet: 'Standard toggle light switch 15A.',
    reasoning: 'Stocked locally. 334 reviews. Standard switch.',
  },
  {
    id: 'lowes-308-gfci-outlet-20a',
    kind: 'supply',
    title: 'GFCI Ground-Fault Circuit Interrupter 20A',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/GFCI-Outlet-20A',
    priceUsd: 14.98,
    priceDisplay: '$14.98 each',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 201 },
    snippet: 'GFCI 20A outlet for wet locations.',
    reasoning: 'Code-required for bathrooms/kitchens. 201 reviews.',
  },
  {
    id: 'grainger-309-conduit-fittings',
    kind: 'supply',
    title: '1/2" EMT Conduit Connector Assortment (20-piece)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Conduit-Connectors',
    priceUsd: 16.99,
    priceDisplay: '$16.99',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 78 },
    snippet: '20-piece assortment of EMT conduit connectors.',
    reasoning: 'All common connector types. Professional quality.',
  },

  // ============================================================================
  // DRYWALL & FINISHING SUPPLIES (8 fixtures)
  // ============================================================================
  {
    id: 'hd-401-sheetrock-1-2-drywall',
    kind: 'supply',
    title: 'USG Sheetrock 1/2" Drywall Sheet 4x8',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Drywall-Sheetrock',
    priceUsd: 14.98,
    priceDisplay: '$14.98 per sheet',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 289 },
    snippet: 'Standard weight drywall, 1/2" thickness for interior walls.',
    reasoning: 'Stocked locally, 30min pickup window. Standard drywall.',
  },
  {
    id: 'lowes-402-drywall-joint-compound',
    kind: 'supply',
    title: 'USG Sheetrock Joint Compound 5 Gallon',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Joint-Compound',
    priceUsd: 34.98,
    priceDisplay: '$34.98 per bucket',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 156 },
    snippet: 'Ready-mixed joint compound 5-gallon bucket.',
    reasoning: 'Best bulk pricing. In stock. Standard compound.',
  },
  {
    id: 'hd-403-drywall-tape-fiberglass',
    kind: 'supply',
    title: 'Drywall Fiberglass Mesh Tape 300ft',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Drywall-Tape',
    priceUsd: 8.98,
    priceDisplay: '$8.98 per roll',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 234 },
    snippet: '300-foot fiberglass mesh tape for drywall joints.',
    reasoning: 'Stocked locally. Self-adhesive. 234 reviews.',
  },
  {
    id: 'lowes-404-corner-bead-metal',
    kind: 'supply',
    title: 'Metal Corner Bead 10ft',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Corner-Bead',
    priceUsd: 3.98,
    priceDisplay: '$3.98 per piece',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.5, count: 178 },
    snippet: 'Metal corner bead for inside corners.',
    reasoning: 'Very local availability. Standard finish bead.',
  },
  {
    id: 'grainger-405-drywall-sanding-sponge',
    kind: 'supply',
    title: 'Drywall Sanding Sponge Assortment (4-pack)',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Sanding-Sponges',
    priceUsd: 12.99,
    priceDisplay: '$12.99 per pack',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.6, count: 89 },
    snippet: '4-pack drywall sanding sponges, multiple grits.',
    reasoning: 'Industrial supplier. All grit sizes included.',
  },
  {
    id: 'hd-406-sheetrock-5-8-fire-rated',
    kind: 'supply',
    title: 'USG Sheetrock 5/8" Fire-Rated Drywall 4x8',
    vendor: 'Home Depot',
    source: 'home_depot',
    url: 'https://www.homedepot.com/p/Fire-Rated-Drywall',
    priceUsd: 24.98,
    priceDisplay: '$24.98 per sheet',
    distance: { miles: 2.1, text: '2.1 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 112 },
    snippet: '5/8" fire-rated Type X drywall for code compliance.',
    reasoning: 'Code-required for certain applications. Stocked.',
  },
  {
    id: 'lowes-407-primer-sealer-drywall',
    kind: 'supply',
    title: 'Zinsser Bulls Eye 1-2-3 Primer 1 Gallon',
    vendor: 'Lowe\'s',
    source: 'lowes',
    url: 'https://www.lowes.com/p/Primer-Drywall',
    priceUsd: 18.98,
    priceDisplay: '$18.98 per gallon',
    distance: { miles: 3.5, text: '3.5 mi away' },
    availability: 'in stock',
    rating: { stars: 4.7, count: 201 },
    snippet: 'Universal primer-sealer. Blocks stains, ready for paint.',
    reasoning: 'Best primer for drywall. 201 verified uses.',
  },
  {
    id: 'grainger-408-drywall-screws',
    kind: 'supply',
    title: 'Drywall Screw Assortment (1-1/4", 1-5/8", 2-1/2")',
    vendor: 'Grainger',
    source: 'other',
    url: 'https://www.grainger.com/product/Drywall-Screws',
    priceUsd: 19.99,
    priceDisplay: '$19.99 per assortment',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'in stock',
    rating: { stars: 4.8, count: 145 },
    snippet: 'All-purpose drywall screw assortment, multiple lengths.',
    reasoning: 'Three common sizes. Industrial quality.',
  },

  // ============================================================================
  // SUBCONTRACTOR LISTINGS (10 fixtures, kind: 'subcontractor')
  // ============================================================================
  {
    id: 'angi-501-framing',
    kind: 'subcontractor',
    title: 'Sonoma Valley Framing Co. — Residential & Commercial',
    vendor: 'Angi',
    source: 'angi',
    url: 'https://www.angi.com/companylist/sonoma-framing',
    distance: { miles: 8.4, text: '8.4 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.9, count: 67 },
    snippet: 'Licensed, bonded, insured. 15 years experience framing.',
    reasoning: 'Verified contractor, 67 reviews averaging 4.9 stars.',
    tags: ['licensed', 'bonded', 'insured', 'background checked'],
  },
  {
    id: 'thumbtack-502-plumbing',
    kind: 'subcontractor',
    title: 'Napa Plumbing Solutions — 24/7 Emergency Service',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/plumbing',
    distance: { miles: 3.1, text: '3.1 mi away' },
    availability: 'available today',
    rating: { stars: 4.7, count: 124 },
    snippet: 'Full-service plumbing. Licensed master plumber on staff.',
    reasoning: 'Available today. 124 verified jobs. Master plumber certified.',
    tags: ['licensed', 'bonded', '24/7 available'],
  },
  {
    id: 'yelp-503-electrical',
    kind: 'subcontractor',
    title: 'Vintage Electric — Residential & Commercial Rewiring',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/vintage-electric-napa',
    distance: { miles: 2.9, text: '2.9 mi away' },
    availability: 'available next week',
    rating: { stars: 4.8, count: 88 },
    snippet: 'Licensed electrician. Panel upgrades, new wiring, troubleshooting.',
    reasoning: 'Closest electrician. 88 reviews at 4.8 stars.',
    tags: ['licensed', 'bonded', 'insured'],
  },
  {
    id: 'thumbtack-504-roofing',
    kind: 'subcontractor',
    title: 'Napa Roofing & Gutters — Full Roof Replacement',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/roofing',
    distance: { miles: 4.2, text: '4.2 mi away' },
    availability: 'available 1 week',
    rating: { stars: 4.6, count: 45 },
    snippet: 'Roof replacements, repairs, gutters, and maintenance.',
    reasoning: 'Specialized roofing. 45 verified projects.',
    tags: ['licensed', 'bonded', 'free estimates'],
  },
  {
    id: 'angi-505-hvac',
    kind: 'subcontractor',
    title: 'Climate Control HVAC Solutions — New Installation & Service',
    vendor: 'Angi',
    source: 'angi',
    url: 'https://www.angi.com/companylist/climate-hvac',
    distance: { miles: 6.1, text: '6.1 mi away' },
    availability: 'available 3-5 days',
    rating: { stars: 4.7, count: 89 },
    snippet: 'HVAC installation, maintenance, emergency service. Licensed, certified.',
    reasoning: 'EPA certified technicians. 89 verified installations.',
    tags: ['licensed', 'EPA certified', 'warranty included'],
  },
  {
    id: 'thumbtack-506-concrete',
    kind: 'subcontractor',
    title: 'Concrete Specialists — Foundation & Flatwork',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/concrete',
    distance: { miles: 5.3, text: '5.3 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.8, count: 56 },
    snippet: 'Foundations, driveways, patios. 20+ years in concrete work.',
    reasoning: '56 verified projects. Specialized concrete contractor.',
    tags: ['licensed', 'bonded', 'workmanship guarantee'],
  },
  {
    id: 'yelp-507-painting',
    kind: 'subcontractor',
    title: 'Premium Painting — Interior & Exterior',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/premium-painting-napa',
    distance: { miles: 7.2, text: '7.2 mi away' },
    availability: 'available next week',
    rating: { stars: 4.6, count: 73 },
    snippet: 'Quality painting service. Prep, prime, finish included.',
    reasoning: '73 reviews for interior and exterior painting.',
    tags: ['licensed', 'insured', 'satisfaction guaranteed'],
  },
  {
    id: 'google-maps-508-masonry',
    kind: 'subcontractor',
    title: 'Stone & Brick Masonry — Custom Stonework',
    vendor: 'Google Maps',
    source: 'google_maps',
    url: 'https://maps.google.com/stone-brick-masonry',
    distance: { miles: 9.1, text: '9.1 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.9, count: 41 },
    snippet: 'Custom stone and brick work. Fireplaces, walls, arches.',
    reasoning: 'Highest-rated masonry specialist. 41 reviews at 4.9.',
    tags: ['licensed', 'custom design', 'high-end work'],
  },
  {
    id: 'angi-509-drywall-finishing',
    kind: 'subcontractor',
    title: 'Pro Drywall Finishing — Texture & Mudding',
    vendor: 'Angi',
    source: 'angi',
    url: 'https://www.angi.com/companylist/pro-drywall',
    distance: { miles: 4.7, text: '4.7 mi away' },
    availability: 'available next week',
    rating: { stars: 4.7, count: 52 },
    snippet: 'Expert drywall finishing. Texture, mudding, sanding, painting prep.',
    reasoning: '52 verified finishing projects. Professional quality.',
    tags: ['licensed', 'fast turnaround', 'smooth finish guarantee'],
  },

  // ============================================================================
  // SERVICE LISTINGS (6 fixtures, kind: 'service')
  // ============================================================================
  {
    id: 'yelp-601-inspection',
    kind: 'service',
    title: 'Bay Area Home Inspections — Comprehensive Reports',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/bay-area-home-inspections-napa',
    priceUsd: 425,
    priceDisplay: '$425 per inspection',
    distance: { miles: 3.8, text: '3.8 mi away' },
    availability: 'available next 3 days',
    rating: { stars: 4.9, count: 76 },
    snippet: 'Licensed inspector. Detailed reports with photos and video.',
    reasoning: 'Comprehensive inspections. 76 verified reports.',
    tags: ['licensed', 'certified', 'detailed reports'],
  },
  {
    id: 'google-maps-602-soil-testing',
    kind: 'service',
    title: 'Geotechnical Solutions Inc — Soil Analysis & Reports',
    vendor: 'Google Maps',
    source: 'google_maps',
    url: 'https://maps.google.com/geo-solutions-napa',
    priceUsd: 600,
    priceDisplay: '$600–$1,200',
    distance: { miles: 9.2, text: '9.2 mi away' },
    availability: 'available 1 week',
    rating: { stars: 4.8, count: 41 },
    snippet: 'Professional soil testing, compaction analysis, engineering reports.',
    reasoning: 'Licensed engineers. Specialized soil testing.',
    tags: ['licensed engineers', 'insurance included'],
  },
  {
    id: 'thumbtack-603-permit-assistance',
    kind: 'service',
    title: 'Napa Building Permits & Compliance Services',
    vendor: 'Thumbtack',
    source: 'thumbtack',
    url: 'https://www.thumbtack.com/ca/napa/permit-services',
    priceUsd: 350,
    priceDisplay: '$350 base + filing fees',
    distance: { miles: 2.0, text: '2.0 mi away' },
    availability: 'available immediately',
    rating: { stars: 4.7, count: 52 },
    snippet: 'Expedite permit approvals, handle city submissions, compliance checks.',
    reasoning: 'Closest permit service. Local expert. 52 projects.',
    tags: ['local expert', 'no surprise fees'],
  },
  {
    id: 'yelp-604-design',
    kind: 'service',
    title: 'Modern Build Studio — Architecture & Design Consulting',
    vendor: 'Yelp',
    source: 'yelp',
    url: 'https://yelp.com/biz/modern-build-studio-napa',
    priceUsd: 150,
    priceDisplay: '$150/hr',
    distance: { miles: 5.1, text: '5.1 mi away' },
    availability: 'available 2-3 weeks',
    rating: { stars: 4.9, count: 29 },
    snippet: 'Licensed architects. Design consultation, construction drawings.',
    reasoning: 'Licensed architects. BIM-certified. 29 design projects.',
    tags: ['licensed architects', 'BIM certified'],
  },
  {
    id: 'craigslist-605-dumpster-rental',
    kind: 'service',
    title: 'Bay Area Dumpster Rental — Same-Day Delivery',
    vendor: 'Craigslist',
    source: 'craigslist',
    url: 'https://craigslist.org/napa',
    priceUsd: 425,
    priceDisplay: '$425–$550/week',
    distance: { miles: 2.5, text: '2.5 mi away' },
    availability: 'available today',
    rating: { stars: 4.6, count: 38 },
    snippet: '10-40yd dumpsters. Fast delivery, flexible rental terms.',
    reasoning: 'Same-day delivery available. Competitive pricing.',
    tags: ['same-day delivery', 'flexible duration'],
  },
];
