-- ROLLBACK for canonical-demo-row reconciliation (lane: fix/canonical-demo-polish)
-- Target: public.command_center_projects, row 55730cd3-5225-493d-8b5c-49086d942565
-- Project: knowledge-gardens-prod (vlezoyalutexenbnzzui) — SHARED prod
-- Captured: 2026-06-08T05:55:23Z
-- Generated by Postgres format(%L/%s) from the live row, so quoting is exact
--   (note client_name=NULL, numerics unquoted, sqft as text).
-- Restores ONLY the 8 columns this lane changes. Companion lossless full-row
--   snapshot: command_center_projects_55730cd3_20260608T055523Z.json
-- To roll back: run this statement once against vlezoyalutexenbnzzui.

UPDATE public.command_center_projects SET name='Modern farmhouse in Marin', sqft='4950', budget_amount=2320300, phase='PLAN', progress=15, client_name=NULL, raw_input='1,800 sf custom modern farmhouse in Marin County, CA. 3 bed, 2 bath. Slab-on-grade foundation. Mid-grade finishes. New construction on existing lot. Want to start late summer 2026.', ai_summary='Alright, here''s how I''d read it: 2,800 sf custom build in Marin lands in the $900k–$1.2M range delivered. Marin County permitting is strict and slow — Title 24 envelope compliance plus seismic detailing (CRC R403.1 on slab + R301.2 wind/seismic) push the structural and envelope cost. Long-lead items: custom millwork (8–10 weeks), Title 24-compliant glazing (6–8 weeks), and the seismic engineering review before permit (often 4–6 weeks). Slab-on-grade simplifies sub-floor but you''ll pay extra for the engineered fill if the lot has any drainage concerns. Foundation rebar schedule for Marin seismic zone is denser than coastal SD — your concrete sub needs to know what they''re bidding.

Jurisdiction: Marin County, CA

Here''s where I''d start:' WHERE id='55730cd3-5225-493d-8b5c-49086d942565';
