-- 20260816_brand_assets_3d_model_type.sql
--
-- Admit 3-D specimens into the shared brand_assets catalog.
--
-- WHY: scripts/media/ publishes GLB meshes generated by FLUX -> Trellis -> Draco.
-- Two live CHECK constraints reject them today, verified read-only on
-- vlezoyalutexenbnzzui (knowledge-gardens-prod) on 2026-08-16:
--
--   brand_assets_asset_type_check  admits motion, emblem, plate, glyph, icon,
--     illustration, texture, background, crest, poster, moment  -- no '3d-model'
--   brand_assets_generator_check   admits midjourney, firefly, flux, ideogram,
--     runway, kling, sora, human, upload, wan                    -- no 'flux+trellis'
--
-- This migration ADDS those two values and changes nothing else. It is additive
-- and idempotent: every previously-legal value stays legal, so no existing row
-- can be invalidated and re-running it is a no-op.
--
-- NOT APPLIED. Shared multi-tenant prod — founder applies, supervised.
-- scripts/media/03_upload_studio.py preflights for these values and refuses to
-- write until this has landed, rather than silently mis-tagging specimens as
-- 'illustration'/'flux' to squeeze past the constraint.

begin;

-- Guard: fail loudly if the table is not the shape this migration was written
-- against, instead of dropping a constraint we did not actually inspect.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.brand_assets'::regclass
      and conname  = 'brand_assets_asset_type_check'
  ) then
    raise exception 'brand_assets_asset_type_check is absent — schema drifted, review before applying';
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.brand_assets'::regclass
      and conname  = 'brand_assets_generator_check'
  ) then
    raise exception 'brand_assets_generator_check is absent — schema drifted, review before applying';
  end if;
end $$;

alter table public.brand_assets
  drop constraint brand_assets_asset_type_check;

alter table public.brand_assets
  add constraint brand_assets_asset_type_check
  check (asset_type = any (array[
    'motion', 'emblem', 'plate', 'glyph', 'icon', 'illustration',
    'texture', 'background', 'crest', 'poster', 'moment',
    '3d-model'                                    -- added 2026-08-16
  ]));

alter table public.brand_assets
  drop constraint brand_assets_generator_check;

alter table public.brand_assets
  add constraint brand_assets_generator_check
  check (generator is null or generator = any (array[
    'midjourney', 'firefly', 'flux', 'ideogram', 'runway',
    'kling', 'sora', 'human', 'upload', 'wan',
    'flux+trellis'                                -- added 2026-08-16
  ]));

-- Post-condition: insert and immediately delete a row using BOTH new values.
-- If either constraint still rejects them the transaction aborts and nothing
-- ships — so a partially-applied migration cannot go unnoticed.
do $$
declare probe_id uuid;
begin
  insert into public.brand_assets
    (bucket, storage_path, filename, mime_type, slug, title,
     asset_type, garden_scope, generator, status, visibility, key)
  values
    ('brand-assets', '__migration_probe__/3d.glb', '3d.glb', 'model/gltf-binary',
     '__migration_probe_3d__', 'migration probe',
     '3d-model', 'bkg', 'flux+trellis', 'draft', 'private', '__migration_probe_3d__')
  returning id into probe_id;
  delete from public.brand_assets where id = probe_id;
end $$;

commit;

-- DOWN (manual): restore the pre-2026-08-16 value lists. Only safe once every
-- row using the added values is retired or re-tagged, or the ALTER will fail.
--
-- alter table public.brand_assets drop constraint brand_assets_asset_type_check;
-- alter table public.brand_assets add constraint brand_assets_asset_type_check
--   check (asset_type = any (array['motion','emblem','plate','glyph','icon',
--     'illustration','texture','background','crest','poster','moment']));
-- alter table public.brand_assets drop constraint brand_assets_generator_check;
-- alter table public.brand_assets add constraint brand_assets_generator_check
--   check (generator is null or generator = any (array['midjourney','firefly',
--     'flux','ideogram','runway','kling','sora','human','upload','wan']));
